### ISSUE TITLE
How to use use Oboe with blocking components in the pipeline

### ISSUE THREAD

**Issue by ShariqM** [google/oboe#358] opened 2019-01-20 03:20 UTC
Hey, thanks for building Oboe, it's great and fast! I'm working on an audio pipeline which involves a blocking call and I was hoping to get some design guidance from the Oboe team.

Overview: I'm using TfLite to process audio data. The rough idea is it takes 8ms of raw audio data and spits out 8ms of processed audio data, it takes about 6ms to do this computation so it should be able to run in real-time with a 8ms delay. I'm wondering how I can plug this system into the pipeline of samples/LiveEffect. I believe the main difficulties that arise from this are 1) This processing is blocking and 2) It has a fixed size input & output.

Priorities: Low-latency is the number one priority.

My idea:
- Build a RecordingManager.cpp class that continuously reads from mRecordingStream and writes to a CircularBuffer1.
- Build a TfLiteProcessor.cpp which continuously reads 8ms from CircularBuffer1, processes with TfLite, and then writes to CircularBuffer2.
- Have the onAudioReady() callback read from CircularBuffer2 

Questions:
- Is this the optimal low-latency design?
- How should I build the RecordingManager.cpp? Using Futures<> and a thread safe CircularBuffer? Should I use oboe/src/fifo/FifoBuffer.cpp?
- Is it better to just write to the mPlayBack stream rather than using CircularBuffer2+callbacks()?

Thanks for any help!

**Comment by dturner** [comment] 2019-01-21 19:31
Great question! 

Your approach seems good, however, you might be able to simplify it by having just 2 threads: 

1) Recording/processing thread 
- Blocking read from recording stream until you have 8ms of data
- Process with TfLite
- Non blocking write to CircularBuffer

2) onAudioReady callback performs non-blocking reads from CircularBuffer

> Is this the optimal low-latency design?
 
For optimal latency you'll need to use a callback on the playback stream. Also: 

- Make sure you clear all data out of the recording stream before you actually start the whole process, this will avoid you starting with extra latency between input and output
- Set the output stream buffer size to 2*burst sizes, perf mode=LowLatency and sharing mode=Exclusive
- Keep an eye on how much data is being read vs written to your CircularBuffer. You might need to increase the amount of data you initially read from the input stream to avoid underrunning the output stream. 

> How should I build the RecordingManager.cpp? Using Futures<> and a thread safe CircularBuffer? Should I use oboe/src/fifo/FifoBuffer.cpp?

I wrote an example of a non-blocking queue here which you could probably hack for your own data: https://github.com/google/oboe/blob/master/samples/RhythmGame/src/main/cpp/utils/LockFreeQueue.h

> Is it better to just write to the mPlayBack stream rather than using CircularBuffer2+callbacks()?

No because you won't be able to get a low latency playback stream by doing writes this way

Good luck!

**Comment by ShariqM** [comment] 2019-01-21 20:31
Thank you so much! This is really helpful, I will update you with my results.

**Comment by ShariqM** [comment] 2019-01-30 15:57
Forgot to update you - Yes this technique worked very well thanks again. Not sure if I should close this or leave it open for others.

**Comment by dturner** [comment] 2019-01-30 17:18
That's really great to hear, glad the approach worked. 

I will add a section in our documentation which will link back to questions like this which might be helpful to the wider developer community. 

Leaving open until I've done that.

**Comment by Artaches** [comment] 2019-05-30 03:03
I have a related question. What if you just do the tflite processing right in onAudioReady() callback? I've prototyped this and found that if the processing time is greater than setFramesPerCallback(#frames), then AAudio flips out and eventually even crashes the phone.  To reproduce, adding the following to the LiveEffect.cpp is enough:
`#include <unistd.h>
...
// in onAudioReady()
usleep(10 * 1000);      // 10ms
`
Could be be fixed by flushing the streams once in a while?

**Comment by ShariqM** [comment] 2019-06-18 03:30
Hi @dturner. Thanks again for your help earlier, but I'm having some new issues with my implementation. It was working previously, but I changed one thing:
- Before I was using a sample rate of 8khZ in the play&record Stream, this worked flawlessly.
- After I switched to the default sample rate of my phone, 48kHz, I started getting underruns.

I believe this is because before the Android Resampler was being used and now it's not which I think affects buffering on the output. I'm not sure how to resolve my issue. Earlier you suggested:

"""
Keep an eye on how much data is being read vs written to your CircularBuffer. You might need to increase the amount of data you initially read from the input stream to avoid underrunning the output stream.
"""

Could you elaborate on this? I think this may be my issue.

**Comment by ShariqM** [comment] 2019-06-18 06:09
Here's a copy of my git diff from LiveEffect: https://pastebin.com/raw/sNeykq7Y

And my logs: https://pastebin.com/raw/dYyit5c9

Interestingly, the method seems to work fine for a few seconds and then onAudioReady() stops being called, leading to the queue becoming larger and larger. Then the recordingStream->reads() start failing for some reason.

Running on a Pixel 2 if that matters.

**Comment by ShariqM** [comment] 2019-06-18 23:29
This issue does not arise on Nexus 5X, so there seems to be an issue with Oboe and Pixel 2. It may be this issue: https://github.com/google/oboe/issues/557 or something more specific to non-blocking reads.

**Comment by dturner** [comment] 2019-06-21 16:21
Please share the full source for your app and I'll try to take a look.

**Comment by ShariqM** [comment] 2019-06-24 03:41
@dturner Thanks! If you open LiveEffect in this repository you will hear the audio glitch: https://github.com/ShariqM/oboe-358

It only happens on a Pixel 2 from my limited testing. It happens frequently with a USB-C headset and only sometimes without one, as described in #557

**Comment by dturner** [comment] 2020-09-15 14:16
Closing due to inactivity. @ShariqM hopefully you solved the glitching issues. Please post a new question here or on StackOverflow if not.

**Closed by dturner** 2020-09-15 14:16 UTC
Labels: question
