### ISSUE TITLE
Understanding FramesPerCallback / kBufferQueueLength / Buffer Size

### ISSUE THREAD

**Issue by cerupcat** [google/oboe#736] opened 2019-12-21 00:30 UTC
Android Version(s): Any running OpenSL
Android Device(s): Google Pixel 2
Oboe Version: 1.3

**Short Description**

I have an app that has both audio input and output. When using OpenSL, I get consistent cracks/pops in my output stream. When running systrace, I can see that the buffer starts at 192 and randomly hits 0 every once in a while, causing a glitch.

I tried using `setFramesPerCallback` to a larger number than the default `192` and while the callback does show `numFrames` as larger, systrace still shows `192` when full and still produces glitches.

If I change `kBufferQueueLength` (which is hardcoded within the oboe) to a number larger than `2` (its default value), the glitches go away and systrace shows a larger multiple.

Since it's not ideal to alter the hardcoded values `kBufferQueueLength` within oboe and `setFramesPerCallback` doesn't improve the glitches, what would be the correct solution?

**Comment by dturner** [comment] 2019-12-23 16:32
The correct solution is to call [`setBufferSizeInFrames`](https://google.github.io/oboe/reference/classoboe_1_1_audio_stream.html#a06e3f9e133b3a75515e7793939d1cd03) in order to set the buffer size. 

You should set this as a multiple of the burst size (which can be obtained using) [`getFramesPerBurst`](https://google.github.io/oboe/reference/classoboe_1_1_audio_stream.html#ac160acb656515814fa6fdd157c131a0a).

Usually you want to set the buffer size to 1-4 times the burst size, so an example call could be: 

`audioStream->setBufferSizeInFrames(4 * audioStream->getFramesPerBurst())`.

**Comment by dturner** [comment] 2019-12-23 16:32
Please let me know if that solves the issue for you. If I don't hear back within 7 days I'll assume the issue is fixed.

**Comment by cerupcat** [comment] 2019-12-23 18:50
@dturner my understanding is that `setBufferSizeInFrames` only affects `AAudio` though. Is that correct? Basically, I don't see a way of changing the buffer size for OpenSL since systrace always reports the `2 * framePerBurst.` If I change the `kBufferQueueLength` though, the size reported by systrace does change.

**Comment by dturner** [comment] 2019-12-24 10:31
> my understanding is that setBufferSizeInFrames only affects AAudio though. Is that correct?

When OpenSL is being used Oboe uses an intermediate buffer (in opensles/AudioStreamBuffered.cpp) and `setBufferSizeInFrames` changes the size of that buffer. One reason for this is that an OpenSL stream's buffer size cannot be changed once it's been opened, so Oboe has to provide this functionality.    

There's been quite a bit of ongoing discussion about whether changing OpenSL's underlying `numBuffers` has any effect on underrun protection. Our internal research showed that it didn't but did increase latency, however, the behaviour you're seeing suggests it does. 

If you don't change `kBufferQueueLength`, does calling `setBufferSizeInFrames` have any effect on your glitches/underruns? 
 
Related: https://github.com/google/oboe/issues/464

**Comment by cerupcat** [comment] 2019-12-25 00:01
When using AAudio, changing `setBufferSizeInFrames` does improve glitches and systrace shows that the underlying buffer size is indeed changing. 

However, when using OpenSL, setting `setBufferSizeInFrames` has no impact on glitches and systrace shows no change in the underlying buffer size. This is likely because `setBufferSizeInFrames` only has an impact with OpenSL when NOT using a callback and I'm using a callback.

Changing `kBufferQueueLength` does improve glitches though and does show a change in the underlying buffer size when using OpenSL. So, it seems making `kBufferQueueLength` configurable or some alternative would help OpenSL devices.

**Comment by philburk** [comment] 2019-12-25 02:02
Thank you Seth, what you describe is true for several recent versions of
Android. We need to figure out which exact versions and how to make optimal
use of openSL ES for each version. That is a major goal of Oboe. So we want
to do that

It would be easy to control the "capacity" of the buffer. The tricky part
is controlling the variable buffer "size" because we would have to manage
how many bursts are queued at one time. We might be able to do that by
querying the depth of the queue.

By the way the intermediate buffer for openSL ES is only used when doing
blocking reads and writes, not when using callbacks.

Thank you for bringing this to our attention.

**Comment by cerupcat** [comment] 2019-12-28 21:54
No problem @philburk. I didn't realize that this changes based on the Android version.

Is there any downside to increasing `kBufferQueueLength` (other than potential latency)? In my case, latency is less important.

**Comment by philburk** [comment] 2019-12-29 22:07
> Is there any downside to increasing kBufferQueueLength (other than potential latency)?

No, I don't think so. One advantage of Oboe being distributed in source code is that you can fork the code and tweak it. Then after we adjust the buffer queue length based on capacity you can use the released version.

I have started a new feature tracker for changing bufferQueueLength based on capacity. #744 
So I am closing this bug as answered.

**Closed by philburk** 2019-12-29 22:07 UTC
Labels: waiting for answer
