### ISSUE TITLE
how do I query output latency for echo cancellation

### ISSUE THREAD

**Issue by yangwuan55** [google/oboe#80] opened 2018-04-10 03:33 UTC
I want to know how to get the delay for output(write data until it real rendered),or is there any way to get the delay?Can I use the buffersize as the play delay?
I want do echo cancel use the webrtc-apm,but the AudioTrack can't get the right delay(I'm not sure if the delay is too long).
So I want to try oboe.
Thanks for help!!

**Comment by niklasdahlheimer** [comment] 2018-04-14 12:28
Hey,
I will try to give you a few hints (and hope, in case of misleading, Phil or Don will correct me :) ).

1. you CAN predict the time audio data needs from getting into the stream until oboe passes it to the DSP, lets call it "buffer-latency"
2. You CAN NOT predict the time from DSP to your speaker. (But their are ways to estimate this. See [5])

About 1)
A good visualisation about the inner workings of a buffer you can find in [1] starting at ~29:00.
You can query the actual buffer size by calling the method getBufferSizeInFrames().
So your buffer-latency is getBufferSizteInFrames()/(framerate), where framerate=samplerate/channelcount.
If your sampleRate is 48kHz, you have 2 AudioChannels (Stereo), your frameRate is 24kHz. 
So if your buffer is filled with 5 brusts with 128 frames each (you can query the frames per burst by calling getDefaultFramesPerBurst()) your buffer-latency is

(5*128)/24kHz = 26ms

Also you can query the maximum buffer-latency by looking at the buffer capacity with getBufferCapacityInFrames()


hopefully helpful sources
[1][https://www.youtube.com/watch?v=Pjgfje52Yv0](https://www.youtube.com/watch?v=Pjgfje52Yv0)
[2][https://developer.android.com/ndk/guides/audio/audio-latency.html](https://developer.android.com/ndk/guides/audio/audio-latency.html)
[3][https://github.com/google/oboe/blob/master/FullGuide.md](https://github.com/google/oboe/blob/master/FullGuide.md)
[4][https://larsimmisch.github.io/pyalsaaudio/terminology.html](https://larsimmisch.github.io/pyalsaaudio/terminology.html)
[5][https://source.android.com/devices/audio/latency_measure](https://source.android.com/devices/audio/latency_measure)

Greeting Niklas

**Comment by yangwuan55** [comment] 2018-04-16 02:58
Thank you so much!谢谢你!
I will study these.

**Comment by yangwuan55** [comment] 2018-04-16 10:54
If I want get the right delay for all android devices,I shoud measure the delay for every devices and save to a device_delay_list,is it right?

**Comment by dturner** [comment] 2018-04-16 14:02
Great answers @niklasdahlheimer. Just a couple of things to add:

> you CAN predict the time audio data needs from getting into the stream until oboe passes it to the DSP, lets call it "buffer-latency"

This is almost correct. The buffer size determines the latency between your app and the Android audio framework. It (unfortunately) does not account for latency from the Android audio framework to the audio device. 

There are, however, a few methods of obtaining the "app to audio device rendering" latency: 

From API 19: Use AudioTrack.getTimestamp (*in Java only*)
From API 24: Use this same method in C++ via JNI using AcquireJavaProxy. [Example code](https://github.com/googlesamples/android-audio-high-performance/blob/master/SimpleSynth/app/src/main/cpp/audio_player.cc#L306)
From API 26: You can use OboeStream::getTimestamp. [Example code](https://github.com/google/oboe/blob/master/samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp#L212) 

There are 2 caveats with this approach to calculating latency: 

1) It relies on the audio device reporting *accurate* timestamps. All Google devices I've tested are accurate, but others may have varying levels of accuracy. 
2) It does not account for any audio device to transducer (headphones, built-in speaker etc) latency. Particularly on the built-in speaker path sometimes latency can be introduced by DSP to improve the acoustic properties of final audio (e.g. bass boost, echo cancellation). This is why you often see "best with headphones" on games/apps which are audio latency sensitive. 

> If your sampleRate is 48kHz, you have 2 AudioChannels (Stereo), your frameRate is 24kHz.

This is a common source of confusion. "sampleRate" nearly always refers to "sampleRate per channel" so even if you have 10 channels your frameRate will still be 48kHz, with each frame containing 10 samples. 

With this in mind if you had a buffer of 5 "bursts" and each burst is 128 frames the latency would be: 

(5 * 128) / 48000 = 0.01333s = 13.33ms

To answer @yangwuan55 
> If I want get the right delay for all android devices,I shoud measure the delay for every devices and save to a device_delay_list,is it right?

I would try the "get timestamp" approach above first. If that doesn't work out then try one or all of the following. 

You could measure delay manually on different devices, and that is indeed what some developers do. It definitely gives the most accurate results. Although the process of acquiring and testing Android devices (and testing them on different O/S versions) can be expensive and time consuming, depending on the number of models you test. If you go down this road I can recommend getting a WALT device: https://github.com/google/walt which will allow you to test the output latency in isolation (and is what we use to test new Pixel devices). 

Another approach is to include a "loopback" test in your app which runs when the app is first run. The app plays a simple sound (like a sine wave) and measures the time taken for that sound to reach the built-in microphone. This measurement gives you the "round-trip latency" (ouput+input+app). If you just want the output latency then a rough estimate is to subtract about 3ms off that figure as input latency is typically much lower than output latency (source: https://github.com/google/walt/blob/master/docs/AudioLatency.md). 

If you're writing an app which requires the use of headphones (meaning the sound played cannot be heard at the built-in microphone), such as a karaoke app, you can implement a "clap track". The app plays a clap sound at regular intervals and the user claps along whilst the app records the clap sounds. Assuming the user is able to clap exactly when they hear the clap the app can measure the difference between the clap played and the clap recorded in order to obtain the round-trip latency figure.

**Comment by yangwuan55** [comment] 2018-04-17 02:44
How about add a api to the android framework,let the oem offer the delay of the device in the futrue?
Just a suggestion.

**Comment by philburk** [comment] 2018-04-27 22:55
Please see this related bug:
https://github.com/google/oboe/issues/69

Note that knowing the reported latency will not be precise enough for echo cancellation. You will still need to run an adaptive filter that sync up with the actual echo.

The timestamps are only accurate enough for AV sync (lip sync).

**Comment by philburk** [comment] 2018-05-01 23:58
I added calculateLatencyMillis() in this Pull Request.
https://github.com/google/oboe/pull/84

Can we close this?

**Comment by jbloit** [comment] 2018-05-11 09:54
@philburk from which API level is the calculateLatencyMillis() available? (I'm looking for a solution that can work from level 19)

**Comment by philburk** [comment] 2018-05-12 18:45
It requires AAudio, which was added in API 26, Oreo Cookie.

I am closing this because we added calculateLatencyMillis().
Unfortunately we cannot go back and add functionality to OpenSL ES.

**Closed by philburk** 2018-05-12 18:45 UTC

**Comment by niklasdahlheimer** [comment] 2018-06-28 07:39
I do not want to reopen this issue, but maybe @dturner, @philburk or someone else could specifiy the term "audio device", the point where the presentation timestamp is coming from. So is it:

- HAL (probably not, because its in the native framework)
- ALSA in the Linux Kernel
- Audio Codec Hardware
- AD/DA-Converter
- Analog device, i.e the line out, speaker or the microphone

?

I see that the term is coming from other audio-frameworks, but I can not find a precise defintion.
I do not think, that it's somewhere beyond the Audio Codec, so maybe you can share some experience how big the expected latency from there to the analog device could be (If we asume using of headphones, so without the DSP latency).


[[1] Android Framework](https://source.android.com/devices/audio/)
[[2] Graphic from geeknizer](http://geeknizer.com/wp-content/uploads/2013/05/android-audio-architecture.jpg)

**Comment by niklasdahlheimer** [comment] 2018-06-28 10:31
> From @dturner 
> From API 24: Use this same method in C++ via JNI using AcquireJavaProxy. Example code
> From API 26: You can use OboeStream::getTimestamp. Example code

Referring to [this issue](https://github.com/google/oboe/issues/40) and the `AudioStreamBuilder::isAAudioRecommended()` method comment in AudioStreamBuilder.cpp, AAudio will only be supported from API 27 on. 
So in  [95,2%](https://developer.android.com/about/dashboards/#google-play-install-stats) of the cases oboe would choose to use OpenSL ES. I totally get that you can not add functionality to OpenSL ES. But **would it be possible to implement the getTimestamp for openSL ES in oboe, using the Android configuration Interface via AquireJavaProxy**?
Because oboe encapsulates the OpenSL ES objects, it seems like it's not possible to query the timestamp, from the outside of oboe, so the only option would be to change over to OpenSL ES completely.

**Comment by dturner** [comment] 2018-06-28 11:20
> would it be possible to implement the getTimestamp for openSL ES in oboe, using the Android configuration Interface via AquireJavaProxy?

Yes, sure it would. In fact, we have been discussing a way of passing the Java environment to Oboe so that Oboe can query the relevant audio APIs itself (e.g. for getting the native sample rate for built-in audio devices). 

Is it easy? No, not really. It's a bit of a pain to pass the JNIEnv to C++ elegantly (should it be cached between calls? should the client have to pass it every time?). I'm planning on hacking on some ideas for it next week. I'll update progress on https://github.com/google/oboe/issues/116

**Comment by stereomatch** [comment] 2018-07-10 21:38
yangwuan55,

I did some preliminary practical tests for latency using the AAudio echo demo.

What I found was that the latency varied i.e. there was considerable jitter.

You can try to reproduce the experiment.  Plug a headset with built-in mic into the earphone jack of your android device.  Run the AAudio echo sample app.  Place one of the headset's earphones near a second android device's built in microphone.  Run an audio recorder app on the second android device.

Now use the second android device to record some environmental sound (stand some feet away from the devices and snap your fingers to generate pulses).

The second android device will hear (and be recording to a file) - your finger snap sound.  Meanwhile that same sound will go through the first android device (AAudio echo sample app) and be output on the first android device's earphones.

So the second android device will hear your finger snap over the air, and also hear it from the earphones (coming from the first android device).


After you have snapped your fingers a few times, take the audio recording that was made by the second android device, and view it in Audacity or some audio editor app.  You will be able to see the finger snap pulses, and notice that it occurs in pairs.  Measure the time-difference between these pulses.


You will notice that sometimes it is as low as 40 milliseconds, but sometimes it can be as large as 100 milliseconds.


This difference is also audible - as you use the AAudio echo sample app, you will be able to hear that when it starts off it is quite low latency, but then later as it runs the latency can increase.

**Comment by yangwuan55** [comment] 2018-07-13 06:17
@stereomatch Yes it was,I can only do this work between differents devices and write the result to a property file.At the beginning I thought there has some way to get the latency,anyway I thanks every body who care about this question.

**Comment by stereomatch** [comment] 2018-07-18 18:37
yangwuan55 and philburk:

One thing I forgot to add - I would like to emphasize that all metrics that try to measure latency as a statistical estimate (i.e. running some program to estiamte latency and then giving average) is not going to be useful to someone who wants to use a single latency measurement to measure distance or range-finding or stereo separation.

If statistical estimate for latency is to be made, then along with the average, there should also be a measure of spread.  However, even this is not as reliable, because it does not account for the 1/10 bad latency measurement (that may happen from missed audio frames etc.).

Regarding the above experiment - I am not sure what is the cause of the latency variation - and why anecdotally the latency is very good initially, but as the AAudio loop runs (sending input data to output data in the AudioProcess.cpp file for instance) - that latency seems to increase.

My guess is that if the same experiment was run, where AAudio was being reset periodically, perhaps the latency would not stray as much - as you would be catching AAudio in it's initial stages.

**Comment by stereomatch** [comment] 2018-07-18 19:58
yangwuan55 and philburk:

In the AAudio echo demo code - in AudioProcess.cpp (which is being called by the playback thread) - I haven't tested it, but perhaps sometimes the data from recording thread is not a full buffer, in which case we output partial buffer for playback.  Which may not play it until it gets the full buffer.  As a result, only on next call to process() in AudioProcess.cpp do we get a full buffer, and when we send it to play, then play plays it - thus there may be a delay in playback.

If this is true (I haven't done this testing yet) - then in process() one solution could be to just ignore small sized buffers.  This way, on next call to process(), if that is a full buffer we send that - and so the playback will always have the latest data, or it will not play anything.  This of course will create glitches - but if the intent is to never build up a backlog in output for playback, then doing a test with this setup may not lead to latency increasing over time.

Another test one could do is in AudioProcess.cpp - in process() method do a system time check - and log the times or differences, and the buffer size that was send into process().  This would reveal if any partial buffers are being sent because of a mismatch between playback thread and recording thread - as a result of which a buffer backlog is being built up (for output for playback).  Assuming that that is the reason for the latency increase with time.

This could be logged to a in-memory buffer (if one doesn't want to use logcat) - and a histogram of the results output at the end for checking what is going on with the buffer arrival times, and buffer sizes.

**Comment by stereomatch** [comment] 2018-07-18 22:16
yangwuan55 and philburk:

Ok, I can confirm that something like the above is happening.

In the AAudio echo demo, in AudioEffects.cpp - process(), if you log the "numFrames" value, these are the types of values you get on a Nexus 4 running Oreo 8.1 (custom ROM):

0
240
240
240
240
240
240
240
240
128
112
240
240
240
240
240
240
240
16
224
...


That is, there is a pattern - every 8th or 9th call to process() does not deliver a full frame - but a partial one - which is then compensated in the next call to process().

In the above:
128 + 112 = 240
16 + 224 = 240

That is, whenever there is a partial buffer, the next call to process() is quicker (after 1 millisecond or so, instead of the usual 4 or 5 milliseconds) which delivers the rest of the frame (to complete the 240 number).

I wonder if this is causing the delivery of the frame to the playback thread for play, to be slightly delayed and thus mis-timed for playback, thus missing it's slot to play at the right time.

**Comment by stereomatch** [comment] 2018-07-19 01:15
yangwuan55 and philburk:

In the EchoAudioEngine.cpp - dataCallback(), this is being done:

    /**
    * If there's not enough audio data from input stream, fill the rest of buffer with
    * 0 (silence) and continue to loop
    */
    numFrames -= frameCount;
    if (numFrames > 0) {
      memset(static_cast<int16_t *>(audioData) + frameCount * outputChannelCount_,
	     0, sizeof(int16_t) * numFrames * outputChannelCount_);
    }

That is, even when frameCount < numFrames i.e. got < 240, still we are filling rest of buffer with zeros and behaving as if it is a full frame.  This is probably where the extra data is being send for playback.

That is the 128 + 112 = 240 cases mentioned above - where a 240 frame arrives as partial frames via two calls to AudioEffect.cpp - process() - is actually generating two full 240 sized frames.  So no wonder the playback is being fed extra data.  That is, the adding of zeros to fill a partial buffer in above code is what is adding that extra data to the playback pipeline.

**Comment by stereomatch** [comment] 2018-07-19 03:38
Looking forward to any criticism of the above explanation.

**Comment by stereomatch** [comment] 2018-07-19 15:45
I apologize for the convoluted (and incrementally developed) explanation above - I have also confused some terms - mixing up frameCount and numFrames.

However, I have cleaned up the explanation in the new issue thread, so hopefully it is more understandable:

https://github.com/google/oboe/issues/165
AAudio full-duplex latency increasing over time reason identified and needs fix to dataCallback() API in AAudio #165

**Comment by stereomatch** [comment] 2018-07-23 18:51
@philburk  Do you find the above explanation of latency increasing plausible ?  If so, is there a way for developers to flush the playback pipeline ?

**Comment by stereomatch** [comment] 2018-07-30 19:35
To reproduce the latency variation, run AAudio echo sample - choose:
Recording device: built-in microphone
Playback device: built-in earphone speaker
Keep volume low enough that you don't have heavy feedback, but if you snap your fingers, you should hear a pulse train - 2 or 3 echoes at least.

Now listen to the earphone speaker with your ear, as you snap your fingers.  Each snap will create a pulse train (echoes due to feedback).

Initially the pulse train will be very close together, but then 20 seconds later the pulse train period will noticeably seem to be longer.

However, a bit later the pulse train period will again become smaller.

This suggests the audio latency doesn't just increase monotonically and then become stable.  Instead it increases, then is reset to the minimum, then a bit later it is more.  This suggests there is resetting going on of the playback pipeline (or something like that) - which is resetting the latency back to low levels.  However there is a great deal of variation in it (which means there is probably data loss on playback pipeline as well).

I urge AAudio engineers to do this test on their android devices (Oreo 8.1) to see if they can reproduce this issue.
