### ISSUE TITLE
RhythmGame Delay On Tap

### ISSUE THREAD

**Issue by rg4real** [google/oboe#645] opened 2019-09-25 09:49 UTC
Android Version(s): 5.1
Android Device(s): Meizu M2 Mini
Oboe Version: Latest 

**Short Description**
Taking steps from here:
https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html?index=..%2F..index#5

After finishing «Play multiple sounds» and tapping on a screen I experience a delay of a CLAP sound with a backing track. I tap precisely on a clap in a song and the clap is delayed.

Is it a tap event delay? Maybe an example in a repo should be optimized to reduce tap latency? If that is possible.

P.S. No experience with C++, sorry for wacky bug report.

**Comment by dturner** [comment] 2019-09-25 15:52
Please could you do the following whilst the app is running: 

- Open a terminal
- Run the following command `adb shell dumpsys media.audio_flinger`
- Paste the output into this issue

My suspicion is that your phone (Meizu M2 Mini) is not reporting rendering timestamps accurately and/or does not support low latency audio streams.

**Comment by rg4real** [comment] 2019-09-26 06:53
```
Clients:
  pid: 800
  pid: 976
  pid: 1458
Notification Clients:
  pid: 288
  pid: 800
  pid: 976
  pid: 1458
  pid: 16104
  pid: 23419
Global session refs:
  session   pid count
    14889   976     1
    24704 16104     1
    24721   976     1
    24722   800     1
    24723   800     1
    24727   800     1
    24728   800     1
Hardware status: 0
Standby Time mSec: 3000

Output thread 0xf4573000:
  Normal frame count: 1024
  Last write occurred (msecs): 949264
  Total writes: 1272415
  Delayed writes: 0
  Blocked in write: no
  Suspend count: 0
  Sink buffer : 0xf4520000
  Mixer buffer: 0xf45b4000
  Effect buffer: 0xf451f000
  Fast track availMask=0xfe
  I/O handle: 2
  TID: 885
  Standby: yes
  Sample rate: 44100
  HAL frame count: 1024
  HAL buffer size: 8192 bytes
  Channel Count: 2
  Channel Mask: 0x00000003 (front-left, front-right)
  Format: 0x3 (pcm32)
  Frame size: 8
  Pending config events: none
  AudioMixer tracks: 0x0000003e
  FastMixer not initialized
  Stream volumes in dB: 0:-8, 1:-inf, 2:-inf, 3:0, 4:-5, 5:-inf, 6:0, 7:-inf, 8:-inf, 9:-inf, 10:-12, 11:0, 12:0, 13:0, 14:0
  Normal mixer raw underrun counters: partial=0 empty=0
  5 Tracks of which 0 are active
    Name Active Client Type      Fmt Chn mask Session fCount S F SRate  L dB  R dB    Server Main buf  Aux Buf Flags UndFrmCnt
       3     no    800    1 00000001 00000003   24722   4800 S 1 48000  -inf  -inf  000012C0 0xf4520000 0x0 0x600         0 
       5     no    800    1 00000001 00000003   24728   4800 S 1 48000  -inf  -inf  000012C0 0xf4520000 0x0 0x600         0 
       4     no    976    1 00000001 00000003   14889   8256 S 1 44100  -inf  -inf  00002040 0xf45b4000 0x0 0x600         0 
       1     no    800    1 00000001 00000003   24727   4800 S 1 48000  -inf  -inf  000012C0 0xf4520000 0x0 0x600         0 
       2     no    800    1 00000001 00000003   24723   4800 S 1 48000  -inf  -inf  000012C0 0xf4520000 0x0 0x600         0 
  1 Effect Chains
    1 effects for session 0
	In buffer   Out buffer   Active tracks:
	0xf451f000  0xf451f000   0
	Effect ID 9:
		Session Status State Engine:
		00000   000    000   0xf1c283f0
		Descriptor:
		- UUID: AE12DA60-99AC-11DF-B456-0002A5D5C51B
		- TYPE: A122ACC0-5943-11E0-ACD3-0002A5D5C51B
		- apiVersion: 00020000
		- flags: 00040248 (conn. mode: insert, insert pref: first, volume mgmt: implements control, device indication: requires updates, input mode: not set, output mode: not set, mode indication: required)
		- name: MAM2_Coretex_A9 "1.0.174.0" Aug 10 2016 12:44:41
		- implementor: Waves Audio ltd.
		- Input configuration:
			Frames  Smp rate Channels Format Buffer
			01024   44100    00000003      1 (pcm16) 0xf451f000
		- Output configuration:
			Buffer     Frames  Smp rate Channels Format
			0xf451f000 01024   44100    00000003 1 (pcm16)
		1 Clients:
			  Pid Priority Ctrl Locked client server
			 1458        0  yes    yes      0      0

Reroute submix audio module:
 route[0] rate in=0 out=0, addr=[]
 route[1] rate in=0 out=0, addr=[]
 route[2] rate in=0 out=0, addr=[]
 route[3] rate in=0 out=0, addr=[]
 route[4] rate in=0 out=0, addr=[]
 route[5] rate in=0 out=0, addr=[]
 route[6] rate in=0 out=0, addr=[]
 route[7] rate in=0 out=0, addr=[]
 route[8] rate in=0 out=0, addr=[]
 route[9] rate in=48000 out=48000, addr=[]

```

**Comment by dturner** [comment] 2019-09-26 07:37
The codelab version of the RhythmGame app is hard coded to 48000 frames/sec. Your phone has a native sample rate of 44100 which means you won't get a low latency stream. You could try the latest version (on master branch) of the RhythmGame app, or you could just change the sample rate in your current version with the caveat that the sounds will be pitched down slightly. 

Its on our roadmap to update that codelab to point to the latest version.

**Comment by rg4real** [comment] 2019-09-26 08:00
@dturner , wow! And the good news are that althogh it's not on a low latency stream it plays perfectly smoothly in terms of intervals. I am creating a metronome. No random delays, everything os precisely on a beat. It's an impressive job! And I was trying to make this shit work for a month :)

Okay, got. I missed that part about frames.

Thanks!

**Comment by rg4real** [comment] 2019-09-26 08:02
@dturner , is it necessarily to match frames or it's «nice-to-have»? I think I did not see a message from AudioFlinger about not being accepted to low latency stream. (but I could miss that)

Other times I was getting that message but no in a RhythmGame project.

**Comment by dturner** [comment] 2019-09-26 09:38
Closing this since it's not a bug, but feel free to add comments on the closed bug.

**Closed by dturner** 2019-09-26 09:38 UTC
Labels: bug
