### ISSUE TITLE
Glitches since update to Android 10 on Pixel 2XL

### ISSUE THREAD

**Issue by balegoff** [google/oboe#633] opened 2019-09-16 11:14 UTC
Android Version(s): Android 10
Android Device(s): Pixel 2XL
Oboe Version: commit fa595e1

Since I updated my device to the new Android 10 the day of the release (September 3rd), I experience audio glitches in my app. These glitches don't sound like pops due to classical underruns, but more like a file encoding glitch.

Here is a recording of the issue, you can hear it at 0:05.
[polaris_glitch.wav.zip](https://github.com/google/oboe/files/3615949/polaris_glitch.wav.zip)

Here is what shows up in logcat (errors only) when I launch the app:

```
2019-09-16 13:09:41.177 1257-1285/? E/system_server: Invalid ID 0x00000000.
2019-09-16 13:09:41.225 7847-7847/? E/eteaure.polari: Unknown bits set in runtime_flags: 0x8000
2019-09-16 13:09:41.435 603-603/? E/SELinux: avc:  denied  { find } for service=audio pid=894 uid=1041 scontext=u:r:audioserver:s0 tcontext=u:object_r:audio_service:s0 tclass=service_manager permissive=0
2019-09-16 13:09:41.443 788-13029/? E/libc: Access denied finding property "persist.audio.out_mmap_delay_micros"
2019-09-16 13:09:41.445 788-13029/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2019-09-16 13:09:41.462 788-2192/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2019-09-16 13:09:41.462 788-2192/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2019-09-16 13:09:41.463 788-2192/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2019-09-16 13:09:41.463 788-2192/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
```

Let me know if you need more info.

**Comment by philburk** [comment] 2019-09-17 03:24
The WAV file sounded pretty good except I heard an odd "zzoop" sound between 5.20 and 5.30 seconds. Is that the glitch you heard?

What was your app doing? Was it generating music and it created a glitch?

Or were you recording music and the recording was corrupted?

How often does it glitch? Is it periodic or random?

I notice the WAV file is at 44100 Hz. Did you open the stream at 44100 Hz? That makes a big difference.

If you need to record at 44100 Hz then the latest Oboe in master branch has its own resampler.
You can enable it using:

    builder->setSampleRateConversionQuality(oboe::SampleRateConversionQuality:High);

It might not glitch.

**Comment by balegoff** [comment] 2019-09-17 07:54
Hi Phil,

The zzoop you mention between 5.20 and 5.30 is precisely the issue I'm describing.

My app is a drum machine generating sound on the device. It was generating sound while the glitch appeared indeed. The weird thing here is that this never happened before I upgraded to Android 10. Even when installing quite old builds of my app, I get the issue with this new configuration.

The glitch seems to appear randomly, can be once every 3 min, or several times in 10 sec.

To generate the audio example, I recorded the output of my phone into my computer, so 44.1kHz is simply my DAW sample rate. The process on my phone is done at 48kHz, as returned by the device.

**Comment by philburk** [comment] 2019-09-17 17:15
OK, a few more questions then. When you open the output stream, do you set 

- PerformanceMode?
- SharingMode?

That will determine the data path.

Were you playing through speakers or a USB device?

Were you also recording at the same time?

I cannot reproduce this on a Pixel 2 XL running Android 10 using OboeTester.

The zzoop has some interesting properties.  At 5.330 seconds there is a displaced section that is exactly one msec. So maybe the read and write pointers are crossing in the DSP buffers.

Try using 
    builder->setSharingMode(haringMode::Exclusive)
    ->setBufferSizeInFrames(8*48);

Does that reduce the glitching?

Are you seeing any underruns?

    stream->getXRunCount();

What is your exact build name? You can get it from Settings.

**Comment by balegoff** [comment] 2019-09-18 11:17
The two modes you mention are set to:

`
builder->setSharingMode(oboe::SharingMode::Exclusive);
builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
`

The issue happens through the built in speakers, or by using headphones through the USB-C to Jack adapter.

I'm not doing recording at the same time, just outputting audio.

Here is the Xrun test I put at the end of onAudioReady: 

`
if((audioStream->getXRunCount().value() - mPreviousXRunsCount) != 0) {
        mPreviousXRunsCount = audioStream->getXRunCount().value();
        LOGE("XRuns detected");
}
`

- With same configuration as before: 

getXRunCount doesn't report any underrun when I hear a zzoop, but when my Pixel screen goes black, sometimes I hear a very little pop (not zzoop), and at the same time an underrun is detected.

- With setBufferSizeInFrames(8*48):

I don't hear any zzoop, nor pop when the screen goes black. getXRunCount doesn't report any underrun. 

My build name is QP1A.190711.020

Are there anything new to Android 10 that could impact audio performances ?

**Comment by dturner** [comment] 2019-09-26 09:28
Please could you run a systrace whilst the issue is occurring and attach it to this issue:

    systrace.py --time=5 -o trace.html -a com.example.yourpackagename audio sched freq

> getXRunCount doesn't report any underrun when I hear a zzoop,

This means it could be CPU bandwidth issue. Might be worth checking out this article: https://medium.com/@donturner/debugging-audio-glitches-on-android-ed10782f9c64

**Comment by philburk** [comment] 2019-09-27 00:27
> With setBufferSizeInFrames(8*48) I don't hear any zzoop,

Then the issue is probably caused by underruns, with the DSP and CPU counters being very close.
This may be due to a combinations of problems in the modeling of the DSP timing for MMAP and CPU performance issues. There is an ongoing effort to solve these issues.

As a workaround, experiment with various buffer sizes that are multiples of the framesPerBurst.

**Comment by dturner** [comment] 2019-10-02 17:30
Please supply the systrace so we can investigate further

**Comment by philburk** [comment] 2019-10-02 19:03
Also please let us know the exact build number for Android. There are multiple Q versions.
For example, I am currently testing: 10 QQ1A.190827.001

**Comment by balegoff** [comment] 2019-10-02 19:42
Here are two systrace files with a zoop heard during capture.
[systrace_zoops.zip](https://github.com/google/oboe/files/3683049/systrace_zoops.zip)

My Android build number is 10 QP1A.190711.020

**Comment by philburk** [comment] 2023-08-31 01:50
I believe this was caused by some problems in the IsochronousClockModel, which tracks the DSP position.
It had trouble adjusting to discontinuities in the DSP position.
These have been fixed in Android 12 and 13.

**Closed by philburk** 2023-08-31 01:50 UTC
Labels: bug

**Comment by meteaurestudios** [comment] 2023-09-04 16:43
I actually managed to fix the issue back in the days by using the `DefaultDataCallback::setThreadAffinity()` method provided in oboe samples.
