### ISSUE TITLE
Engine stops with ErrorTimeout on Samsung A21s when BufferCapacity is specified

### ISSUE THREAD

**Issue by apleton** [google/oboe#1239] opened 2021-03-31 14:54 UTC
Android version(s): 10 
Android device(s): Samsung A21s
Oboe version: 1.5.0
App name used for testing: Hello Oboe
 
**Short description**
When I call setBufferCapacityInFrames(8192) on the AudioStreamBuilder in Hello Oboe, the error callback will be called with the error ErrorTimeout (-885). It seems that it's the combination setPerformanceMode(oboe::PerformanceMode::LowLatency) and setBufferCapacityInFrames(8192)  that creates the issue. 

The A21s is the first device where I see that issue. Should I remove setBufferCapacityInFrames call ? What is the best practice here? 

**Steps to reproduce**
- In Samples project, add `->setBufferCapacityInFrames(8192)` to the AudioStreamBuilder in HelloOboeEngine.cpp (method createPlaybackStream). 

```
oboe::Result HelloOboeEngine::createPlaybackStream() {
    oboe::AudioStreamBuilder builder;
    return builder.setSharingMode(oboe::SharingMode::Exclusive)
        ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
        ->setFormat(oboe::AudioFormat::Float)
        ->setDataCallback(mLatencyCallback.get())
        ->setErrorCallback(mErrorCallback.get())
        ->setAudioApi(mAudioApi)
        ->setChannelCount(2)
        ->setDeviceId(mDeviceId)
        ->setFormat(oboe::AudioFormat::Float)
        ->setBufferCapacityInFrames(8192)
        ->openStream(mStream);
}
```

- Launch the HelloOboe app on a Samsung A21s

**Expected behavior**
App emits sound when surface is touched

**Actual behavior**
- No sound when surface is touched
- Error -885 (timeout) printed in logs

**Device**
Samsung A21s

**Comment by philburk** [comment] 2021-04-07 17:10
@apleton - Thanks for the report. Can you reproduce this in your office? Do you have an A21S?

We would need to see logs from the open call to the error callback. Can you capture some logcat and attach (not paste) it as a file?

If you can get a bugreport file then please create a bug here:

https://issuetracker.google.com/issues?q=componentid:192705

and then attach the bugreport file to that bug.

**Comment by dturner** [comment] 2021-04-21 10:17
Seems like the A21S has other problems as well: https://github.com/google/oboe/issues/1247

**Comment by apleton** [comment] 2021-04-21 12:17
Here is the log in the test described in the first post
[A21sOboeLog.txt](https://github.com/google/oboe/files/6350673/A21sOboeLog.txt)

**Comment by philburk** [comment] 2021-05-13 21:48
Thanks for the log. it's very helpful. I can see that HelloOboe is opening and closing the stream multiple times when the app launches! This is a bug and it can trigger some weird race conditions. I think the TIMEOUT in the log is due to this.

I tried to reproduce this on a Samsung A51S but could not repro the bug.  But I was able to clean up the launch behavior in HelloOboe.  When that is merged, we can see if it fixes this bug.

**Comment by philburk** [comment] 2021-05-26 01:28
I will assume that the changes in HelloOboe fixed this problem. Please comment if not.

**Comment by apleton** [comment] 2021-05-26 06:40
The issue is still there. Just add the line 
`->setBufferCapacityInFrames(8192)`
to the openPlaybackStream method.

However I made more testes, with a capacity of 4096, there is no issue anymore. 
Questions : 
- how can we get the maximum capacity of the buffer to avoid that issue
- Do we have to specify that maximum capacity or can we leave it to kUnspecified. What would be the drawback of that ?

**Comment by philburk** [comment] 2024-01-24 23:34
I just noticed the new comments and reopened this issue.

> Do we have to specify that maximum capacity or can we leave it to kUnspecified. 

Leaving it kUnspecified is fine. AAudio should make the buffer as large as it needs.

If you want to be able to have widely variable latency then you can set a higher capacity.
then call setBufferSizeInFrames() to adjust the latency.

**Comment by philburk** [comment] 2024-01-31 22:50
Because this is on Android 10, I will not report it to Samsung.
The app should not request 8192 frames of capacity with low-latency because 8192 frames is 170 msec.
Just leave it unspecified.

We will add an internal CTS test to make sure that a stream can be opened even with a very high requested capacity.

**Closed by philburk** 2024-01-31 22:50 UTC
Labels: bug, Samsung
