### ISSUE TITLE
Using vivo X9 Plus will cause ear-returning noise

### ISSUE THREAD

**Issue by WangShuo1143368701** [google/oboe#390] opened 2019-02-25 09:04 UTC
demo for LiveEffect have noise （vivo X9 Plus）

reset Commits on Dec 31, 2018  is no problem。

**Comment by philburk** [comment] 2019-02-25 14:10
I think that some vivo phones do not implement float properly. See issue
#201.
We are working on a workaround that will use integer instead of float.

**Comment by dturner** [comment] 2019-03-05 17:57
Duplicate of #201

**Closed by dturner** 2019-03-05 17:57 UTC
