### ISSUE TITLE
aaudio capture on some vivo devices glitch

### ISSUE THREAD

**Issue by Jimmy198901** [google/oboe#1380] opened 2021-08-10 13:36 UTC
Android version(s): android10
Android device(s): vivo
Oboe version:1.6
App name used for testing: 
Oboe Tester
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)

aaudio capture glitch when performance is AAUDIO_PERFORMANCE_MODE_LOW_LATENCY

the wav file is following

[oboe_recording_20210810-205703.wav.zip](https://github.com/google/oboe/files/6962065/oboe_recording_20210810-205703.wav.zip)

**Steps to reproduce**

start oboe tester recorder with the following settings
![Screenshot_2021_0810_210314](https://user-images.githubusercontent.com/85278816/128876093-a7ef8a8b-9a57-48de-a8aa-3c69cb2e9279.jpg)

**Device**
![Screenshot_2021_0810_211345](https://user-images.githubusercontent.com/85278816/128876283-f900802b-fd3c-4e6d-843c-f55414e25e2a.jpg)

![Screenshot_2021_0810_211404](https://user-images.githubusercontent.com/85278816/128876319-92210105-4666-4fe8-92c9-ce5bdb383218.jpg)

**Comment by philburk** [comment] 2021-08-11 16:41
@Jimmy198901 - Thanks for the report and for including the WAV file. That was extremely helpful.
The distortion does not sound like buffer underruns dropout. It sounds like the recording has a high frequency amplitude modulation. This could be caused by tuning configuration files, or bad state in the low level audio path.

Can you please try some experiments?
Please try with MMAP disabled to see if it is MMAP specific.
Please try with Input Margin set to "2" to detect DSP position errors.
Please try with PerfMode: NONE

Then reboot the device and try these tests again.

You say it happens on "some Vivo devices". Does that mean it happens on some Vivo models and not others. Or some units of the same model? 

How does it sound if you use a different voice recording app?

**Comment by Jimmy198901** [comment] 2021-08-13 11:20
I took the following test, and the results are

1、try with MMAP disabled
The recorded sound has the same problem
2、try with AAUDIO_PERFORMANCE_MODE_NONE
The recorded sound is normal
3、try with Input Margin set to "2"
The first recorded sound has the following problems，The second time and after the recorded sound is normal

[oboe_recording_20210813-183857.wav.zip](https://github.com/google/oboe/files/6981940/oboe_recording_20210813-183857.wav.zip)

When reboot the device and try these tests again，the problems is the same

When I use the aaudio api with the same parameters on our app，the problems is the same

We have received reports of the following models:

<img width="276" alt="vivo" src="https://user-images.githubusercontent.com/85278816/129348653-5c1318bf-ef08-470f-a0b4-4a44d30e69e4.png">

I only tested V2020A because I don't have any other models on hand

**Comment by philburk** [comment] 2021-08-15 01:41
@Jimmy198901 - Thanks for the extra details! I have enough information to report this to Vivo.

I have one last request. The latest OboeTester V2.2.2 has an improved "DATA PATHS" test.  It is designed to automatically detect these sorts of problems before the device ships.

OboeTester V2.2.2 source is on GitHub and the App is on the Play Store.

Could you please run the DATA PATHS test on your Vivo 2020A?
Put phone in a quiet room
Press DATA PATHS
Turn up volume to about 80%
Press START
It will play tones over various data paths and record over various data paths.
After about 3-5 minutes it will finish.
You can then SHARE the report in an email to yourself and then attach it as a file on this Issue.
I will share that report with Vivo.

I know I am asking a lot. But this will automatically run a bunch of tests that would take you an hour to run manually.

**Comment by Jimmy198901** [comment] 2021-08-16 07:53
@philburk , Thanks for help solve this problem, the DATA PATHS test report file is following

[vivo_data_paths_test_report.log](https://github.com/google/oboe/files/6990642/vivo_data_paths_test_report.log)

I forgot to mention an important point，The problem is obvious only when plugging in headphones，so I'm not sure the DATA PATHS test without headphones is going to help

**Comment by philburk** [comment] 2021-08-18 18:47
Both MMAP and Legacy have the same problem. Those datas are completely different above the DSP. So the problem seems to be in the DSP code for the LowLatency path. Probably a bad tuning file. It works fine when NOT in LowLatency mode so we know it is not a hardware problem.

> The problem is obvious only when plugging in headphones

OK, that is an important clue. According to https://www.gsmarena.com/vivo_s7-10347.php
The Vivo S7 does not have a 3.5mm jack. So this appears to be related to the USB jack.

**Comment by xzhan96** [comment] 2023-01-13 06:26
> 

Hi @philburk I find aaudio on vivo V2011A has glitch, but if set Input Margin to 1, all works fine. I see the "Input Margin" setting actually calling AudioStream::waitForAvailableFrames.
My question is if it suitable for I always use AudioStream::waitForAvailableFrames? from the annotation, I think it should not has affect on delay?

**Comment by xzhan96** [comment] 2023-01-30 07:34
> 



> > 
> 
> Hi @philburk I find aaudio on vivo V2011A has glitch, but if set Input Margin to 1, all works fine. I see the "Input Margin" setting actually calling AudioStream::waitForAvailableFrames. My question is if it suitable for I always use AudioStream::waitForAvailableFrames? from the annotation, I think it should not has affect on delay?

I did a delay test, it seems has much negative effects on delay. After using waitForAvailableFrames, even the first parameter |numFrames| is audioStream->getFramesPerBurst(), the delay becomes to 140+ms, vs. before delay only about 30ms.

**Comment by philburk** [comment] 2023-02-02 00:36
> the delay becomes to 140+ms, 

That is an important clue. That means the DSP position is slightly off from where AAudio thinks it is.
The extra latency comes from the CPU reading ahead of the DSP pointer instead of behind it.

You might be able to see this if you run the round trip latency test and look at the result for each value of Input Margin.
The latency should go up slightly each time. If it jumps down then that proves the problem is the incorrect DSP timestamp.

I will pass this information to VIVO.

**Comment by philburk** [comment] 2023-02-02 00:48
@xhan96 - I think the problem you are seeing may be different than what @ Jimmy198901 reported.
Jimmy is seeing problems with Legacy paths so it is not an MMAP problem.
Your problem is specific to MMAP.
So I will move our conversation about the InputMargin to #1686.

**Comment by philburk** [comment] 2023-02-02 01:32
Tracking internally at: [b/267546393](http://b/267546393) | P2 | aaudio capture on some vivo devices glitch, Vivo S7, USB headset

**Comment by philburk** [comment] 2024-05-22 19:16
Vivo never responded. Closing as not actionable.

**Closed by philburk** 2024-05-22 19:16 UTC
Labels: bug, P2
