### ISSUE TITLE
S9 / Note 9 cannot record in mono mode

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#976] opened 2020-08-12 09:35 UTC
Android version(s): 10
Android device(s): Samsung S9 and Note 9
Oboe version: 1.4.2
App name used for testing:  OboeTester and Audio Evolution Mobile Studio
 
**Short description**
Create a recording stream with mono mode, Recording is very low in pitch.

**Steps to reproduce**
OboeTester, Record and Play, set Channels to 1, Record, Play.

**Expected behavior**
Recording is in mono and sounds fine.

**Actual behavior**
Recording has low pitch (but audio clips have the expected length).

**Device**
SM-G960F
No info on the Note 9 since it was a customer report

**Any additional context**
When selecting OpenSLES, recording in mono works fine.
Recording in stereo using AAudio also works fine.

If applicable, please attach a recording of the sound.
[TestRecording.zip](https://github.com/google/oboe/files/5061828/TestRecording.zip)

**Comment by philburk** [comment] 2020-08-12 13:22
This is a duplicate of #824 
There is a workaround in #890, which was merged June 17, 2020.
That workaround is not in the 1.4.2 or 1.4.3 releases.

**Closed by philburk** 2020-08-12 13:22 UTC
Labels: bug
