### ISSUE TITLE
Request: More Documentation of PerformanceModes

### ISSUE THREAD

**Issue by ShariqM** [google/oboe#366] opened 2019-01-30 17:40 UTC
**Context**: I'm trying to use PerformanceMode::LowLatency but I get PerformanceMode::None because my sample rate is too low (8kHz) which is consistent with a comment I see in [2]. I'm not sure I can scale up to 44.1kHz because it results in significantly more computation in my audio processing path.

**Background**: from [1] the performance modes are:
MODE_POWER_SAVING - large buffers + slower data path 
MODE_LOW_LATENCY - small buffers + optimized data path
MODE_NONE - balances the previous two

I understand that for a fixed buffer size, doubling the sample rate results in cutting the latency in half [3].

**Questions**:
- Why does using the optimized data path (in low latency mode) depend on the sample rate?
- MODE_NONE is pretty vague, does it ever use the optimized data path, when?
- If I must use MODE_NONE when I double the sample rate does the latency go down according to [3] still?
- Does using the high priority audio callback() have any effect on the answers to my questions? I was under the impression they don't use buffers but now I'm not sure.

Thanks for any help, Oboe has been a big help for me.

[1] https://developer.android.com/ndk/guides/audio/aaudio/aaudio 
[2] https://github.com/google/oboe/blob/ec8de0feef6df0af28d8de1d85437e2b7620c92e/tests/testStreamOpen.cpp#L76
[3] with a fixed bufferSize of 128 samples, for Fs=8kHz, 16kHz, 32kHz, we get maximum latencies of 16ms, 8ms, and 4ms.

**Comment by dturner** [comment] 2019-01-30 18:14
> Why does using the optimized data path (in low latency mode) depend on the sample rate?

The underlying audio hardware will have a fixed sample rate. Unless you supply audio data at that rate then resampling must be done. Resampling introduces latency. The resampler in the Android framework is designed for a multitude of use cases and therefore will introduce significant (~50ms) of latency. 

In your case it might be better to do all your processing in 8kHz and then upsample at the end

> MODE_NONE is pretty vague, does it ever use the optimized data path, when?

MODE_NONE is a tradeoff between latency and power consumption, it never uses the "optimized" or "fast" path. 

> If I must use MODE_NONE when I double the sample rate does the latency go down according to [3] still?

Sorry, I don't fully understand this question. When using MODE_NONE the majority of the latency will be introduced after you've returned from the audio callback since this is when the underlying audio framework will resample your 8kHz data to the stream's sample rate. 

> Does using the high priority audio callback() have any effect on the answers to my questions? I was under the impression they don't use buffers but now I'm not sure.

You can only obtain a `PerformanceMode::LowLatency` stream if you use an audio callback. Regardless of the performance mode, buffers are always used in the audio pipeline.

**Comment by ShariqM** [comment] 2019-01-30 19:16
I see, so avoiding the Android Resampler at all times is ideal. Also making the target sample rate a integer fraction of 44.1kHz  should make things simpler, maybe 11025Hz. Is this the best design?
- recordingStream and playBackStream at 44.1kHz (or whatever the device recommends)
- recordingStream->read() - read N samples
- Use a fast/simple C++ library to downsample the N samples to (N/4) samples 11025Hz
- Process (N/4) samples
- Use a fast/simple C++ library to upsample (N/4) samples back to N samples at 44.1kHz
- use high priority audio callback for playbackStream

I would use something like N=640

Is there a C++ library you would recommend for resampling? I'm a bit worried that resampling chunks at a time might introduce aliasing and I need a library that is low latency.

Per my other not understood question which maybe isn't as important now - My question was if I use MODE_NONE with mSampleRate=8kHz vs. mSampleRate=16kHz (for both input/output streams) is the latency better with 16khZ? Perhaps it's irrelevant because, as you said, most of latency will come from resampling.

**Comment by dturner** [comment] 2019-02-22 10:32
> Also making the target sample rate a integer fraction of 44.1kHz should make things simpler, maybe 11025Hz. Is this the best design?

The problem is that different audio playback devices have different native sample rates, most commonly 44.kHz and 48kHz. This is why you always need a resampler.

**Comment by dturner** [comment] 2019-04-16 16:54
Docs have been updated.

**Closed by dturner** 2019-04-16 16:54 UTC
