### ISSUE TITLE
Buffer underrun with the hello-oboe example when connected to a bluetooth speaker

### ISSUE THREAD

**Issue by mregnauld** [google/oboe#325] opened 2018-12-22 17:15 UTC
On a Nokia 1 (low-end device with Android Go 8.1), when I test the hello-oboe example, with the device speaker or with the jack plug, it works fine.

But when I run the same code, on the same device, but this time paired with a bluetooth speaker, the sound is played on the speaker, but I have buffer underruns, when I test with the following code on the `AudioStreamCallback::onAudioReady()` function:

```C++
auto underrunCountResult = audioStream->getXRunCount();
if (underrunCountResult.value() > 0)
{
	LOGW("underrun = %i", underrunCountResult.value());
}
```

Do I have to do something specific to handle the bluetooth connection?

**Comment by philburk** [comment] 2018-12-23 23:59
Are you running with OpenSL ES or AAudio?

Bluetooth often uses bigger buffers. So there may be a buffer size issue. Try increasing the buffer capacity.

Also maybe attach a short  logcat of the open start  of the stream. And maybe "adb shell dumpsys media.audio_policy" and "media.audio_flinger".

Do the BT speakers work OK for YouTube?

Try the OboeTester app in the Oboe repository.

**Comment by mregnauld** [comment] 2018-12-24 11:42
Thanks for your answer.

So here is what I tried so far:
- I use AAudio
- I increased the buffer size, even to its max capacity
And I still have underruns, but only when I'm paired to a bluetooth device.

Also, I haven't noticed any problem with the YouTube app playing a song with the bluetooth speaker (does the YouTube app use Oboe?).

I'll continue the next tests.

**Comment by mregnauld** [comment] 2018-12-24 16:00
Also:

- here is the result of `adb shell dumpsys media.audio_policy`: [log1.txt](http://s519716619.onlinehome.fr/exchange/audio/log1.txt)
- here is the result of `adb shell dumpsys media.audio_flinger`: [log2.txt](http://s519716619.onlinehome.fr/exchange/audio/log2.txt)

I ran those 2 commands while playing the sound on the hello-oboe example.

I don't know exactly what I am supposed to find, but I hope it helps.

**Comment by mregnauld** [comment] 2018-12-25 12:48
Also, I just tried with the OboeTester app ("Test Output" page), again on the Nokia 1 (Android Go 8.1) and here is what I get (when I log the `audioStream->getXRunCount()` function, while the device is connected to a bluetooth speaker):

- when I specify AAudio for the API, I got underruns (that said, I can't hear them, but I have logs)
- when I specify OpenSL ES for the API, there is no underrun at all

**Comment by philburk** [comment] 2018-12-26 22:43
media.audio_policy shows

  Device 3:
  - id: 104
  - type: AUDIO_DEVICE_OUT_BLUETOOTH_A2DP
  - address: 2C:41:A1:24:76:88
  - name: Bose Revolve+ SoundLink

media.audio_flinger shows

Output thread 0xa6025100, name AudioOut_BD, tid 30821, type 0 (MIXER):
  I/O handle: 189
  Standby: no
  Sample rate: 44100 Hz
  HAL frame count: 896
  HAL format: 0x1 (AUDIO_FORMAT_PCM_16_BIT)
  HAL buffer size: 3584 bytes
  Channel count: 2
  Channel mask: 0x00000003 (front-left, front-right)
  Processing format: 0x1 (AUDIO_FORMAT_PCM_16_BIT)
  Output device: 0x80 (AUDIO_DEVICE_OUT_BLUETOOTH_A2DP)

with 898 underruns

**Comment by mregnauld** [comment] 2018-12-27 10:34
OK, but as I said in my last message, there are underruns when I use AAudio (and a lot of them), but no underrun when I use OpenSL ES, and again, only when the device is connected to a bluetooth speaker...

**Comment by philburk** [comment] 2018-12-27 20:59
I could not reproduce this on a Pixel 2 with Bluetooth using OboeTester TEST OUTPUT I got a burst size of 882 and a capacity of 10776.

I was able to get glitching if I used Hello Oboe and set buffer size to "1".

> when I specify OpenSL ES for the API, there is no underrun at all

OpenSL ES does not support setBufferSizeInFrames().  I see that Hello Oboe is calling:

        mPlayStream->setBufferSizeInFrames(mFramesPerBurst);

That may be too small. And the LatencyTuner may not be working.  Try setting "Buffer size" to 4 or 8 using the menu in Hello Oboe.

**Comment by philburk** [comment] 2019-10-22 14:40
> when I specify OpenSL ES for the API, there is no underrun at all

getXRunCount() is not supported for OpenSL ES.

@mregnauld What is the status of this Issue? Are you still having the problem?

See discussion in #357 , which seems similar.

Also, have you tried setting the sample rate to 44100? Does that effect latency.

We will try to get a Nokia phone for testing.

**Comment by mregnauld** [comment] 2019-10-22 15:42
@philburk I haven't tried recently, since I gave up on Oboe (at least for the moment) and went to a pure OpenSL ES solution for my project, which works fine so far.

**Comment by philburk** [comment] 2022-04-20 22:04
Closing as obsolete.

**Closed by philburk** 2022-04-20 22:04 UTC
Labels: bug, P1
