### ISSUE TITLE
How to access ECHO_REFERENCE in Oboe / Aaudio

### ISSUE THREAD

**Issue by bmv66** [google/oboe#826] opened 2020-04-21 12:44 UTC
We are developing an advanced signal processing module that does echo compensation, beam forming, noise cancellation, speaker localization and other fancy stuff.
In the past we had beside several mics also reference channels for the echo compensation, using OpenSLES as audio interface and that worked pretty good.
With Android 10, there seems to be new capabilities for audio HAL like ECHO_REFERENCE that should be implemented according to CDD. 
From a system architecture point I wonder how to implement that now in a proper way.
I think this ECHO_REFERENCE is also used for the default echo compensation in the audio effects but it seems that this is not available in Aaudio or Oboe.
My question is how can I access this ECHO_REFERENCE in sync with the microphone channels from Oboe or Aaudio to do an own echo cancellation in our SW ?
The SW is not fist hand intended to work with commercial devices like Android Phones, but with special designed HW based on Android 10.

Thanks a lot !

**Comment by philburk** [comment] 2020-04-26 19:51
You might be able to use the new PlaybackCapture feature in Android 10.

https://developer.android.com/guide/topics/media/playback-capture

You may run into some issues with permissions. But since you are designing custom hardware you can probably get higher permission.

I that doesn't help then I will find someone more familiar with that data path.

**Comment by bmv66** [comment] 2020-04-27 08:45
Hi Phil,
thank you for the reply. Unfortunately I think we cannot use playback capture for various reasons. We use synchronized microphone and HW reference channels feed back from the amplifier for echo cancellation, also for performance reasons we'd like to use the NDK level API like Oboe or AAudio directly.
Would be great if you could forward my question to someone that is familiar with that.

Thanks, Bernd

**Comment by philburk** [comment] 2020-05-21 00:37
> We use synchronized microphone and HW reference channels feed back from the amplifier

The problem is not at the level of Oboe. You need to route audio from your custom hardware into an audio channel.

It sounds like you have deep access to the hardware. Right?
Are you writing your own HALs for this device?
Is this a commercial development or a hobby project?
Are you working with a Technical Account Manager (TAM)  at Google?

**Comment by bmv66** [comment] 2020-05-27 11:56
Yes, we have deep access to the HW, audio HAL is written by the HW manufacturer, so there all options are availabel. Indeed this is a commerical project, and afaik the HW supplier is working with a TAM at google.

I think the discussions we are currently faced is due to the new ECHO_REFERNCNE introduced with Android 10 and that is only available in HAL and with restrictions in JAVA audio API.
For sure it would be possible to to have an "own" audio stream implemented that includes unprocessed microphone and reference channels for echo compensation, but the HW supplier rised concerns about CDD compliance of such an architecture. 

Is there any plan or roadmap, to provide ECHO_REFERNCNE in AAudio/Oboe in later releases ?

**Comment by philburk** [comment] 2020-05-27 23:39
> Is there any plan or roadmap, to provide ECHO_REFERNCNE in AAudio/Oboe in later releases ?

No. That is HAL feature.

> ... we have deep access to the HW, audio HAL is written by the HW manufacturer,
> so there all options are available.

Then maybe the easiest thing for you is to create an input device called "echo", or something you can recognize.  It should just look like a normal input so AudioFlinger will handle it fine.
But inside the HAL, you can route the output you want to capture to that input.
Then in your app just open the "echo" input.

**Comment by bmv66** [comment] 2020-05-28 16:40
> Then maybe the easiest thing for you is to create an input device called "echo", or something you can recognize. It should just look like a normal input so AudioFlinger will handle it fine.
> But inside the HAL, you can route the output you want to capture to that input.
> Then in your app just open the "echo" input.

Do you see any issues with CDD compliance or Android certification with such an architecture ?

thx, Bernd

**Comment by philburk** [comment] 2020-05-31 00:26
> Do you see any issues with CDD compliance or Android certification with such an architecture ?

I don't know. 

Also this is an area for filing Issues with Oboe and your issue is not related to Oboe.
I suggest asking for an answer through your TAM and not in a public forum.
Your TAM can find the right person in Google and set up the right kind of communication.
Closing for now.

**Closed by philburk** 2020-05-31 00:26 UTC

**Comment by philburk** [comment] 2023-07-24 19:08
This is now being tracked internally at:
[b/292564849](http://b/292564849) | P4 | AAudio needs support of hotword and echo reference system input source
