### ISSUE TITLE
Travis CI build shows as success even though the build failed

### ISSUE THREAD

**Issue by dturner** [google/oboe#599] opened 2019-08-08 15:03 UTC
For the following build https://travis-ci.org/google/oboe/builds/568925001 it failed with a compilation error, however, the result is still shown as success. 

We need this fixed quite urgently as we rely on Travis to test our changes to Oboe and samples.

**Comment by ggfan** [comment] 2019-08-20 23:25
just sync[ .ci_tools/build_samples.sh](https://github.com/google/oboe/blob/refactor-samples/.ci_tools/build_samples.sh#L21) to the master branch would fix this one. The root cause is that when you migrated to app-bundle, the array name is "apks", but the checking is against array name "bundles" ( line 21 ), there is no "bundles" variable.

**Comment by philburk** [comment] 2019-08-20 23:29
Fixed in https://github.com/google/oboe/pull/585

**Closed** 2019-08-20 23:29 UTC
Labels: bug, high priority
