### ISSUE TITLE
Record Voice Call using Oboe

### ISSUE THREAD

**Issue by muzeasd** [google/oboe#643] opened 2019-09-23 05:19 UTC
Hello there. First, thanks for the great work.

I need to record voice calls using Oboe. But I can not seem to find a sample which can record both incoming voice as well as outgoing voice at the same time. 

If it is not possible, can I record both incoming an outgoing voices in different files and then merge them using Oboe?

Thanks a lot :)

**Comment by dturner** [comment] 2019-09-26 09:15
I'm 99% sure that the recording of voice calls isn't possible any more, at least on recent versions. Is your experience different?

**Comment by dturner** [comment] 2019-09-26 09:38
Closing this since it's not a bug but feel free to add comments

**Closed by dturner** 2019-09-26 09:38 UTC
Labels: bug

**Comment by muzeasd** [comment] 2019-09-28 19:29
Then how some of the voice call recorders are working? They are available on PlayStore. Can I record incoming voice and outgoing voice in 2 different files and then merge them using Oboe?
