### ISSUE TITLE
[OboeTester] Round Trip Latency cannot be obtained when using Format PCM_I16

### ISSUE THREAD

**Issue by xzhan96** [google/oboe#1246] opened 2021-04-19 07:41 UTC
Android version(s): 10
Android device(s): Oneplus 8
Oboe version: Latest code build
App name used for testing: OboeTester
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
Round Trip Latency cannot be obtained when using Format PCM_I16

**Steps to reproduce**
Just open OboeTester, choose "Round Trip Latency", and set Format to PCM_I16 then click the OPEN button.

**Expected behavior**
Get result

**Actual behavior**
result.text = ERROR_CONFIDENCE

**Device**

ro.product.brand = OnePlus
ro.product.manufacturer = OnePlus
ro.product.model = IN2010
ro.product.device = OnePlus8
ro.product.cpu.abi = arm64-v8a
ro.build.description = OnePlus8-user 10 QKQ1.191222.002 2007160559 release-keys
ro.hardware = qcom
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

**Comment by xzhan96** [comment] 2021-04-22 13:39
@dturner is it a bug or feature missed? I notice that LatencyAnalyzer.h use float to calculate  the latency.

**Comment by dturner** [comment] 2021-04-22 14:09
@philburk and I discussed this yesterday. I think the conclusion was that the latency calculation code only works on floats. @philburk is that correct? If so, what should we do about it?

**Comment by xzhan96** [comment] 2021-04-23 07:02
> @philburk and I discussed this yesterday. I think the conclusion was that the latency calculation code only works on floats. @philburk is that correct? If so, what should we do about it?

Thanks for your conclusion, :-) I still have two question need your confirmation:
1. Is it possible to do type convert to support Int ? or does that will loss the calculation accuracy?
2. Are the "Test Output" and "Test Input" also use LatencyAnalyzer.h? I see those test cases can output latency.
![image](https://user-images.githubusercontent.com/13726257/115831939-d6003000-a444-11eb-8a24-d51f55d49171.png)

**Comment by philburk** [comment] 2021-04-23 14:55
The problem is that when Oboe delivers PCM16 to the latency analyzer it is not handled correctly.
Turning on format conversion would still result in PCM16 going to the analyzer.
The only fix it to convert the PCM16 to FLOAT in OboeTester before the analyzer.
That is not hard. I'll do that. It would be nice to see if formats selection has an effect on latency.

The timestamp.latency is an estimate based on the reported timestamps. We can compare this to the actual measured latency to evaluate the accuracy of getTimestamp().

**Comment by xzhan96** [comment] 2021-04-26 02:28
@philburk Got it, Thanks a lot! 

> That is not hard. I'll do that. It would be nice to see if formats selection has an effect on latency.

For this, can I know when you will implement it?

**Comment by philburk** [comment] 2021-04-30 18:03
Fixed in #1255 
I added experimental support for 24 and 32-bit in S. That will not work in R.
And at the same time I fixed the PCM_I16 problem described here.

**Closed by philburk** 2021-04-30 18:03 UTC
Labels: bug
