### ISSUE TITLE
Stacktrace from NDK Oboe contains private paths

### ISSUE THREAD

**Issue by peterdk** [google/oboe#1190] opened 2021-02-08 23:00 UTC
I don't know if this is easy to fix, but it's a bit messy to see the full buildpath of the NDK so files in a stacktrace when having a crash. 

I am using Oboe 1.5.0 using the pre-built binaries and headers.

```
SIGSEGV Segmentation violation (invalid memory reference) 
    ../../../Users/donturner/Code/workspace-android/oboe/src/common/AudioStream.cpp:201 oboe::oboe_stop_thread_proc(oboe::AudioStream*)
    ../../../Users/donturner/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/type_traits:3501 _ZNSt6__ndk18__invokeIPFvPN4oboe11AudioStreamEEJS3_EEEDTclclsr3std6__ndk1E7forwardIT_Efp_Espclsr3std6__ndk1E7forwardIT0_Efp0_EEEOS6_DpOS7_
    /system/lib/libc.so:293797 0xaa34fba5
    /system/lib/libc.so:110697 0xaa323069
```

To be clear, I am refering to the `/Users/donturner/Code/workspace-android` part. It would be cleaner if it just started at `oboe/src`

**Comment by philburk** [comment] 2021-02-09 19:06
> It would be cleaner if it just started at oboe/src

Sometimes a crash may be due to an error in the developers code.
In that situation it is useful to have the full stack trace.

I am closing as Working as Intended

**Closed by philburk** 2021-02-09 19:06 UTC
