### ISSUE TITLE
Android Settings: "'Hey Google' from any screen" settings leads to no input using OpenSL.

### ISSUE THREAD

**Issue by cerupcat** [google/oboe#789] opened 2020-02-13 18:37 UTC
Android Version(s): Android 10
Android Device(s): Xiaomi Mi 9T
Oboe Version: 1.3

**Short Description**

I have a user who is unable to get microphone input. They sent me the log below and figured out that turning off ''Hey Google' from any screen" fixed the issue. Seen from the logs a constant "use case assigned already in use." Starting the input stream appears to succeed despite receiving no input. Turning off this setting in Android settings fixes the issue.

**Oboe Settings**

- Audio = OpenSL
- Sharing Mode = Shared
- Performance Mode = Low Latency and None (produce the same result)
- Using Full Duplex Code
- Open Input then Output
- Start Output then Input

If applicable, please attach a recording of the sound.

**Log**

[logcat_mi9t.txt](https://github.com/google/oboe/files/4206752/logcat_mi9t.txt)

**Comment by philburk** [comment] 2020-02-14 21:09
(I removed the log from the comment and attached it as a file.)

Thanks for reporting this. It sounds like a hardware resource problem specific to the device. I will file a bug internally.

**Comment by philburk** [comment] 2020-04-08 18:31
Note that the Xiaomi Mi 9T uses a Qualcomm SDM730 Snapdragon:
https://www.gsmarena.com/xiaomi_mi_9t-9738.php

I cannot reproduce this on a Pixel 3a.

The internal bug shared with Xiaomi is b/153567049

**Comment by cerupcat** [comment] 2020-04-08 19:33
Thanks, Phil.

I've had 3 users contact me about this. All are on Xiaomi devices and all
were able to get audio input working by turning off the "from any screen"
setting.
ᐧ

**Comment by cerupcat** [comment] 2020-08-11 04:59
Curious if there’s any solutions to this. I’ve been having more users run into this. Anyone else?

**Comment by philburk** [comment] 2020-09-08 18:16
An engineer from Xiaomi says it has been fixed. I have asked for more details.

**Comment by cerupcat** [comment] 2020-10-19 17:33
@philburk I've had more people seeing this issue on different devices. A fairly large, but minority amount of users have to turn off Google Assistant to get Oboe working.

I've now had this reported on the Remdi Note 7, Android 10.

I'll try to get a larger list of other users that have reported this issue.

**Comment by rpattabi** [comment] 2020-11-05 13:27
@cerupcat Does this issue happen only with OpenSL? Did your users report similar issue with AAudio?

**Comment by rpattabi** [comment] 2020-11-08 06:06
Similar behavior is noted from our user with the following device:

Android: 28 (9)
Device: samsung SM-J530F (samsung j5y17lte) / Samsung Galaxy J5
Build: PPR1.180610.011.J530FXXS7CTF1
Fingerprint: samsung/j5y17ltexx/j5y17lte:9/PPR1.180610.011/J530FXXS7CTF1:user/release-keys

There is one difference with the originally reported issue: This happens with AAudio. For this user, switching off Google Assistant made the input working fine. He also checked that input works fine when not using oboe (and using OpenSL) *without* having to switch off Google Assistant.

It seems silent input only happens with oboe on specific devices, irrespective of audio api. As with Xiaomi, could this be Samsung bug?

PS: It may be noted that when using AAudio `Unprocessed` input preset is used in our case which as per [documentation](https://developer.android.com/guide/topics/media/sharing-audio-input) is not privacy sensitive. However, privacy sensitivity concept started appearing only from Android 10. The above device is running Android 9.

**Comment by cerupcat** [comment] 2020-11-08 17:31
My app is only using OpenSL right now since I’ve been having entirely different issues with AAudio.

If there’s devices experiencing this same issue with AAudio it may be unrelated.

**Comment by rpattabi** [comment] 2020-11-10 11:47
> If there’s devices experiencing this same issue with AAudio it may be unrelated.

This behavior seems to be irrespective of audio api. As per [documentation](https://developer.android.com/guide/topics/media/sharing-audio-input), the input sharing behavior is complex across different types of applications (ordinary, privacy sensitive, in-built, accessibility service). The input sharing behavior also differs across android versions.

It is possible that this complexity resulted in bugs in manufacturer implementations. As @philburk mentioned [above](https://github.com/google/oboe/issues/789#issuecomment-689050952) that Xiaomi confirmed that they had a bug fixed in this regard.

As per our user's testing (explained above), the following is another device exhibiting the similar problem:

```
Android: 28 (9)
Device: samsung SM-J530F (samsung j5y17lte) / Samsung Galaxy J5
Build: PPR1.180610.011.J530FXXS7CTF1
Fingerprint: samsung/j5y17ltexx/j5y17lte:9/PPR1.180610.011/J530FXXS7CTF1:user/release-keys
```

**Comment by cerupcat** [comment] 2020-12-03 19:10
Do we know if there's a way to detect when this happens? I would love to show something to the user so they don't think the app is broken (which they do currently).

**Comment by philburk** [comment] 2022-04-20 22:25
[b/153567049](http://b/153567049) | hotword detector preventing others apps from accessing the microphone on Xiaomi Mi 9T

That bug was fixed by Xiaomi on Q. it uses a Qualcomm Snapdragon SDM730

The similar problem reported by rpattabi above is on a Samsung Exynos. It seems related to #1526.

So closing this Xiaomi related bug.

**Closed by philburk** 2022-04-20 22:25 UTC
Labels: bug, P1
