### ISSUE TITLE
Cant record audio by AudioRecord while oboe is used (LiveEffectEngine)

### ISSUE THREAD

**Issue by erez-git** [google/oboe#1653] opened 2022-11-15 13:06 UTC
Android version(s): 8.0.0
Android device(s): Galaxy S7
Oboe version: master
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
my code is using AudioRecord to record audio. now I added LiveEffectEngine for the live effect and the prev AudioRecord doesn't really record (no exception). The S7 is using oboe opensles. Is there any fix?
(Or maybe is there a way to know which devices can't handle 2 recorders.)

When I force the oboe to use oboe opensles for my device, the AudioRecord works well (including the LiveEffectEngine) and it succeeds to record the mic.

**Steps to reproduce**

**Expected behavior:**
AudioRecord should record the mic while LiveEffectEngine works well

**Actual behavior**
AudioRecord doesn't fail but records nothing (zeros buffers) while LiveEffectEngine works well.

**Device**

Please list which devices have this bug.
If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
for p in \
    ro.product.brand ro.product.manufacturer ro.product.model \
    ro.product.device ro.product.cpu.abi ro.build.description \
    ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
    do echo "$p = $(adb shell getprop $p)"; done
```

**Any additional context**

If applicable, please attach a few seconds of an uncompressed recording of the sound in a WAV or AIFF file.

**Comment by robertwu1** [comment] 2022-11-17 15:05
This is working as intended. Multiple recording streams at once may cause all sorts of unintended behavior.

We do not recommending using both AudioRecord and Oboe at the same time. Can you pipe the input of LiveEffectEngine to both the output of LiveEffectEngine and the other thing you are doing? One app should generally not need to have multiple recording functions at once.

Closing the bug as I don't think it is actionable from us.

**Closed by robertwu1** 2022-11-17 15:05 UTC
Labels: bug
