### ISSUE TITLE
Input preset Unprocessed results in silence on some devices?

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#1006] opened 2020-09-07 04:41 UTC
Android version(s): 10 (API 29)
Android device(s): samsung SM-G965F (samsung star2lte) and more?
Oboe version: 1.4.2
App: [Shruti Carnatic Tuner](https://play.google.com/store/apps/details?id=org.kuyil.shruti) v7.0.2

We migrated our app to use oboe and released it recently. This is a tuner app which listens to incoming sound, detects its pitch, and shows the notes. For the input stream, we use `Unprocessed` as input preset. We know `Unprocessed` gives weaker volume levels and we handled it in our app. On the devices we tested, this is working perfectly. However, we started seeing users report that the note detection is not working on some devices. Based on the interaction with a user, we suspect the samsung device mentioned above produces silence in the input stream. We also asked the user to switch off Google Assistant to ensure that it is not interfering with the input which didn't address the problem.

We think that this may be the case with other devices. As a workaround, we asked the user to switch to our _old engine_ which uses OpenSL ES directly without oboe, and it works for this user. No input preset is set while creating this opensl stream, so we assume it uses `Generic` or whichever is the default.

Is it wrong to expect `Unprocessed` to be working on all the devices? Is there anything we could do about this problem? We're particularly interested in getting input signal without any noise suppression which at times alters the pitch of the sound.

**Comment by rpattabi** [comment] 2020-09-09 05:29
Another device with the same problem:

Android version(s): 8.0 (API 26)
Android device(s): samsung SM-G935F (samsung hero2lte)
Oboe version: 1.4.2

**Comment by dturner** [comment] 2020-09-09 16:54
Thanks for reporting this. I have an SM-G965F so will attempt to reproduce using OboeTester and investigate further.

**Comment by rpattabi** [comment] 2020-09-13 05:01
More devices with the same problem:

Device: Nokia Nokia 7 plus (HMD Global B2N_sprout)
Android: 29 (10)

Device: motorola Moto G (5S) (motorola montana)
Android: 25 (7.1.1)
Oboe: 1.4.2

**Comment by dturner** [comment] 2020-09-14 18:07
I've been testing this today on an Samsung Galaxy S9 SM-G965F (Build PPR.180610.011.G965FXXS7CTA2) running Android 9. 

Here's how I tested this behaviour:

- Load the LiveEffect sample app
- Set the media volume to zero by pressing the volume down button
- Tap start
- Increase the media volume by pressing the volume up button, count the number of presses until feedback occurs. 

I tested this with every input preset (by changing the input stream recording parameters in code). Results:

No input preset: 3 steps
Unprocessed: 8 steps
Camcorder: 8 steps
Generic: 8 steps
VoiceCommunication: 8 steps
VoiceRecognition: 3 steps
VoicePerformance: Failed to open stream (because this preset isn't available on Android 9 - [issue filed](https://github.com/google/oboe/issues/1009)). Related: https://github.com/google/oboe/issues/982)

From this it seems that no preset and `VoiceRecognition` are the loudest, with all others requiring more amplification to meet the feedback threshold. 

@rpattabi Does that match your experience? Which devices/presets are you experiencing silence on?

**Comment by rpattabi** [comment] 2020-09-15 04:28
@dturner Thanks for checking this and providing the results in details. From the results you got, it definitely looks like `Unprocessed` works as expected.

As mentioned, in our app the input level (signal strength) is not an issue. No matter how low the level is, we pick up that signal and process it to get desired results. And these users' reports indicate that the input is completely silent. Unfortunately, we don't have access to the devices for which our users reported the problem. We see that we're also missing the device build versions.

However, the user who reported issue with Samsung Galaxy S9 SM-G965F was running Android 10 (API 29). We don't have the device build version. Android version may have made the difference.

We're indeed surprised that this problem is reported even on devices where AudioApi OpenSL ES is used. As mentioned, if we don't go through oboe and directly use OpenSL ES (where no input preset is set), there is no problem as confirmed by our users.

 Do you have any of the following setup to check?

* samsung SM-G965F (samsung star2lte) with Android 10 (API 29)
* samsung SM-G935F (samsung hero2lte) with Android 8.0 (API 26)
* Nokia 7 plus (HMD Global B2N_sprout) with Android: 29 (10)
* Moto G (5S) (motorola montana) with Android: 25 (7.1.1)

**Comment by dturner** [comment] 2020-09-15 11:23
I have requested an SM-G935F and a Nokia 7 Plus from our lab. It usually takes a couple of weeks for them to be sent out to me. 

In addition, I'll update my SM-G965 to Android 10 to see if I can reproduce the silent behaviour. Low volume is probably acceptable but silence is definitely not.

**Comment by dturner** [comment] 2020-09-15 15:54
I updated my S9 to Android 10 (QPA1.190711.020.G965FXXSBETH2). Results: 

No input preset: 3 steps
Unprocessed: 8 steps
Camcorder: 8 steps
Generic: 3 steps
VoiceCommunication: 8 steps
VoiceRecognition: 2 steps
VoicePerformance: 8 steps

For clarity, fewer steps = more gain on the input. So `No preset`, `Generic` and `VoiceCommunication` are all significantly louder than the other presets.

It seems that only the `Generic` preset had different behaviour on Android 10 (it is louder). I couldn't reproduce getting silence on any preset.

**Comment by rpattabi** [comment] 2020-09-16 04:16
Thanks for checking this. Device build is the one thing we're not sure is the same. We'll see if we can get that information. This issue can be closed if you get similar results on other devices you're waiting for.

We're also trying to come up with a way to reproduce this. If that happens, we'll reopen this.

**Comment by rpattabi** [comment] 2020-09-17 14:15
Another device reported by the user:

* motorola moto g(6) play (motorola aljeter) Android 9 (API 28)

**Comment by rpattabi** [comment] 2020-09-21 08:51
Updated list of devices with this problem (Xiaomi Mi A3 is the new addition):

* samsung SM-G965F (samsung star2lte) with Android 10 (API 29)
* samsung SM-G935F (samsung hero2lte) with Android 8.0 (API 26)
* Nokia 7 plus (HMD Global B2N_sprout) with Android: 29 (10)
* Moto G (5S) (motorola montana) with Android: 25 (7.1.1)
* motorola moto g(6) play (motorola aljeter) Android 9 (API 28)
* xiaomi Redmi Note 6 Pro (Xiaomi tulip) Android 9 (28)
* Xiaomi Mi A3 (Xiaomi laurel_sprout) Android 10 (API 29)

**Comment by dturner** [comment] 2020-09-21 11:03
Please could you supply the exact steps which you're using to reproduce this issue. I've just been testing on a Nokia 7 plus with Android 10 (build 00WW_4_15D_SP02) with input preset `Unprocessed` but cannot reproduce.

**Comment by rpattabi** [comment] 2020-09-21 15:17
Good to know that `Unprocessed` preset works fine on Nokia 7 Plus. Did you check it on Oboe 1.4.2 or the latest on master branch?

We continued to work on this critical problem for our app. We have this theory about how this problem could happen. First to answer your question, we're using duplex stream to read the input (similar to LiveEffect may be). We really didn't need duplex but we had to use duplex stream to work around #778 in Oboe 1.4.2 as we were not able to set callback on input stream. So we set callback on output stream and within that callback we read from input stream (very similar to the one in LiveEffect sample).

This is working fine on our devices. Now with users reporting this issue, we could imagine the possibilities of error while reading from input stream. Consider this example scenario:

1. `output_stream::open()` within duplex stream
1. `input_stream::open()` within duplex stream
1. say `output_stream::onAudioReady()` callback happened
1. say input_stream is not yet ready or whatever the reason, `input_stream->read()` gives error. (We're not sure what are all the situations calling `read()` on a stream could give error).
1. there is such an error and the stream is closed and thus no input received.

Please note this is only theory. We're unable to verify this so far on the device exhibiting this problem. We don't quite understand why you're unable to reproduce the problem with LiveEffect. May be LiveEffect is more tolerant than our duplex implementation and/or waits longer for input stream to be ready.

Now that @philburk fixed #778, we see that we don't have to deal with our duplex kludge. For our app, we could directly set the callback on input stream. We hope this would address this issue if duplex sync is the actual cause for the problem.

**Comment by dturner** [comment] 2020-09-22 11:03
> Did you check it on Oboe 1.4.2 or the latest on master branch?

Latest master

Thanks to @philburk who pointed out that OboeTester can be used to test this (so we have an easily reproducible bug). Here's the steps: 
 
- Load OboeTester
- Tap "Echo input to output"
- Tap "Show settings - INPUT"
- Choose InPreset=Unprocessed
- Tap "Hide settings - INPUT" to show the START button (fixed with https://github.com/google/oboe/pull/1022)
- Tap START (on first run, you will be prompted to allow the app to record, do this, then tap stop, then tap start)
- Make some noise next to the phone

Expected outcome: The noise is heard several hundred milliseconds later (the delay is configurable using the slider)

Actual outcome: No noise is heard. 

I have been able to verify this behaviour on a Moto G5 Plus Android 7.0 Build NPNS25.137-93-14

Bug filed for the Motorola devices: [b/169128498](b/169128498)
Bug filed for the Xiaomi devices: [b/169128839](b/169128839)

**Comment by dturner** [comment] 2020-09-22 11:05
Tested on Samsung Galaxy S7 Edge (SM-G935F) Android 7.0 Build NRD90M.G935FXXU1DQG1. Could not reproduce.

**Comment by rpattabi** [comment] 2020-09-30 05:16
Update:

We were using our adaptation of duplex stream as detailed [above](https://github.com/google/oboe/issues/1006#issuecomment-696182569) to read input stream. As with the recent fixes to oboe, we could directly set callback on input stream and we didn't need duplex stream. With this change, we released [our app](https://play.google.com/store/apps/details?id=org.kuyil.shruti) v7.0.6. It's been a few days and so far no reports of silent input. We'll update this thread if any.

We found some devices reported with this problem through firebase test lab and amazon device farm. We created a test suite which exercises our use of oboe. On these devices, reading input stream within duplex stream yielded 0 frames, that is no frames were read frames at all. This was the reason for silence in the input we observed. On the same devices, we found simple input stream with callbacks (with later oboe commits) worked fine with preset `unprocessed`. We didn't get chance to test other input presets. However, we believe the issue is not due to input presets.

These are the devices we tested on the cloud:

* samsung SM-G965F (samsung star2lte) with Android 10 (API 29)
* samsung SM-G935F (samsung hero2lte) with Android 8.0 (API 26)
* Nokia 7 plus (HMD Global B2N_sprout) with Android: 29 (10)
* motorola moto g(6) play (motorola aljeter) Android 9 (API 28)

**Comment by rpattabi** [comment] 2020-09-30 05:25
@dturner You mentioned about using OboeTester's Input to Output Echo test. In case of `unprocessed` input preset, the level of the input signal will be extremely low. Also, the gain level varies from device to device. So we wonder if such low gain sound is audible on the device's speaker and is loud enough to create feedback loop.

**Comment by rpattabi** [comment] 2020-10-13 05:38
Silence is reported for `Unprocessed` input preset for this device. This is without using duplex stream.

```
Shruti Carnatic Tuner: 93 (7.0.6) <-- using oboe at [ee39453cb1](https://github.com/google/oboe/tree/ee39453cb1637460f7c4321f9d4d7c4f63d544c0)
Android: 28 (9)
Device: asus ASUS_X01AD (asus ASUS_X01A_1)
Build: OPM1.WW_Phone-16.2018.2005.64-20200426
Fingerprint: asus/WW_X01AD/ASUS_X01A_1:9/WW_Phone-202004261144/16.2018.2005.64-20200426:user/release-keys

Native samplerate: 48000 Hz
Native Buffer size: 192 samples
Sustained perf support: false
Current samplerate: 48000 Hz
Audio Engine: oboe stream

Input audioApi: AAudio
Input bufferCapacityInFrames: 4096
Input bufferSizeInFrames: 4096
Input framesPerBurst: 192
Input framesPerCallback: 384
Input inputPreset: Unprocessed
```

**Comment by dturner** [comment] 2020-10-13 20:43
@rpattabi   Could you please provide the build version you tested on Redmi Note 6 Pro and Xiaomi Mi A3？

**Comment by rpattabi** [comment] 2020-10-14 12:12
@dturner We've requested our users who reported the problem on Redmi Note 6 Pro and Xiaomi Mi A3. Will get back to you if we could get this information.

**Comment by dturner** [comment] 2020-10-14 16:47
For now I'm going to recommend switching to `VoiceRecognition` preset as this will give you gain but not any other processing which seems suitable for your use case. Let me know if you agree/disagree.

**Comment by rpattabi** [comment] 2020-10-16 03:27
I agree that when `Unprocessed` is not available or gives silence, `VoiceRecognition` is the alternative preset for it. However, we have issue #911. This means, similar to `Unprocessed`, there are devices that won't do what is expected of `VoiceRecognition`.

**Comment by rpattabi** [comment] 2020-10-16 03:34
Summarizing the list of devices that are reported by our users which imply `Unprocessed` resulting in silence (Please note, we haven't yet been able to verify the silence with `Unprocessed` on these devices):

```
Android: 28 (9)
Device: asus ASUS_X01AD (asus ASUS_X01A_1)
Build: OPM1.WW_Phone-16.2018.2005.64-20200426
Fingerprint: asus/WW_X01AD/ASUS_X01A_1:9/WW_Phone-202004261144/16.2018.2005.64-20200426:user/release-keys

Android: 29 (10)
Device: samsung SM-G975F (samsung beyond2)
Build: QP1A.190711.020.G975FXXU8DTH7
Fingerprint: samsung/beyond2lteeea/beyond2:10/QP1A.190711.020/G975FXXU8DTH7:user/release-keys

Android: 29 (10)
Device: samsung SM-G965F (samsung star2lte)
```

**Comment by rpattabi** [comment] 2020-11-06 07:06
Update: The issue at least for the last list of devices here seem to be related to Google Assistant's "Hey Google" hotword detection. If we switch off Google Assistant, it is found that the input with "Unprocessed" works just fine. See #1066 for the discussion.

**Comment by dturner** [comment] 2020-11-09 14:49
Quick (and possibly now redundant) update from Xiaomi. They tested those devices on build V11.0.6.0.PEKMIXM and were unable to reproduce the issue.

**Comment by rpattabi** [comment] 2020-11-10 04:22
Thanks for this info. As per #789, Xiaomi seems to have fixed "Hey Google" related bug in their build that seems to have caused the reported silence. Hope we can assume this fix is applicable for the Xiaomi devices identified for this issue.

**Comment by dturner** [comment] 2021-07-07 16:51
Let's hope so. Please comment if the bug is still present after updating the Android build.

**Closed by dturner** 2021-07-07 16:51 UTC
Labels: bug, high priority, quirk, requires device
