### ISSUE TITLE
Incorrect channel count reported when when requesting low latency mono input

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1247] opened 2021-04-20 16:35 UTC
Android version(s): 10
Android device(s): Samsung A21s (SM-A217F/DS)
Oboe version: 1.5.1
App name used for testing: OboeTester
 
**Short description**
Requesting a mono low latency input stream results in a stream that reports itself as mono, but appears to contain stereo input data (recording results in the expected downshift with slowdown).

**Steps to reproduce**
Tap on "RECORD AND PLAY". Select Channels: 1 and ensure LOW_LATENCY is selected. Record a brief voice sample in the recorder screen and play back.

**Expected behavior**
Recording sounds normal.

**Actual behavior**
Recording is slowed and downshifted.

**Device**
Samsung A21s (SM-A217F/DS)

```
$ for p in \
>     ro.product.brand ro.product.manufacturer ro.product.model \
>     ro.product.device ro.product.cpu.abi ro.build.description \
>     ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
>     do echo "$p = $(adb shell getprop $p)"; done
* daemon not running; starting now at tcp:5037
* daemon started successfully
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-A217F
ro.product.device = a21s
ro.product.cpu.abi = arm64-v8a
ro.build.description = a21snsxx-user 10 QP1A.190711.020 A217FXXU5BUA2 release-keys
ro.hardware = exynos850
ro.hardware.chipname = exynos850
ro.arch = exynos850
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]
```

**Any additional context**

A workaround in Oboe for this issue would be excellent. We'd also be interested to learn a bit more about when this might occur, and what these two channels might correspond to in the case of unexpected stereo input (front and back mic? something else?).

I had a bit of trouble getting audio uploaded to Github, please let me know if that would be helpful and I'll give it another try.

Thank you very much!

Edit by dturner@: Made the reproduction steps a bit clearer

**Comment by dturner** [comment] 2021-04-21 09:48
Thanks for filing this issue. I attempted to reproduce on a Samsung Galaxy A51 and S9+ (both Exynos CPU devices). Device details: 

```
Galaxy A51 
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-A515F
ro.product.device = a51
ro.product.cpu.abi = arm64-v8a
ro.build.description = a51nsxx-user 11 RP1A.200720.012 A515FXXU4DUB2 release-keys
ro.hardware = exynos9611
ro.hardware.chipname = exynos9611
ro.arch = exynos9610
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

Galaxy S9+ 
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-G965F
ro.product.device = star2lte
ro.product.cpu.abi = arm64-v8a
ro.build.description = star2ltexx-user 10 QP1A.190711.020 G965FXXSFFUB3 release-keys
ro.hardware = samsungexynos9810
ro.hardware.chipname = exynos9810
ro.arch = exynos9810
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

```

I was unable to reproduce the issue on either of these devices which means that this issue is: 

- Not common to all Exynos devices
- Not caused by Android - note that the S9+ has the same Android build as your A21

 Next steps/questions: 

- An audio sample would be really useful so we can confirm that it's definitely stereo data being supplied in a mono stream
- Are there any software updates available for the A21? If so, please could you update and retest.

Assuming this is a bug with that specific device we should be able to add a workaround in Oboe. We'd just need you to confirm that it fixes the issue before merging.

**Comment by chrismanchester** [comment] 2021-04-21 16:25
@dturner thank you very much for looking into this!

> Next steps/questions:
> 
> * An audio sample would be really useful so we can confirm that it's definitely stereo data being supplied in a mono stream

https://soundcloud.com/user-811982266/oboe-recording-20210420-203105

> * Are there any software updates available for the A21? If so, please could you update and retest.

There were, but the result is the same after updating.

> 
> Assuming this is a bug with that specific device we should be able to add a workaround in Oboe. We'd just need you to confirm that it fixes the issue before merging.

I should have mentioned this in the original report, but we have reports from users across about a dozen devices with similar artifacts. As a random sampling I see: Aquaris X Pro, JSN-L21, and MAR-LX1M. I don't have these devices in hand to reproduce the bug in the OboeTester, but the artifact sounds the same.

**Comment by dturner** [comment] 2021-04-21 17:02
Thanks for all the info. The sound recording certainly does sound like a stereo data source being played as mono. 

> There were, but the result is the same after updating.

What's the new build number please? This is so we can keep track of affected builds in case it gets fixed in a future version.

> As a random sampling I see: Aquaris X Pro, JSN-L21, and MAR-LX1M. 

Unfortunately I don't have any of those devices either. I wonder if there's a common link between them, like they all use the same audio codec chip?

The good news is that we may already have run into this [issue here](https://github.com/google/oboe/issues/824) and already have implemented a workaround for [it here](https://github.com/google/oboe/blob/82fff1041c8ba5e82ffb67f373d7d17b59a29411/src/common/QuirksManager.cpp#L90). 

That would explain why I'm not able to reproduce on my Samsung Galaxy S9+ - because the workaround fixes the issue.

If you're able to compile Oboe from source a simple way to test whether the workaround works for the A21 would be to change `QuirksManager::isMonoMMapActuallyStereo()` to always return `true`. Are you able to do that and test it?

**Comment by chrismanchester** [comment] 2021-04-21 18:07
Yes, that is good news! The workaround is effective on this device.

For reference, the new build is: a21snsxx-user 10 QP1A.190711.020 A217FXXU5BUB4 release-keys

**Closed** 2021-04-21 21:33 UTC
Labels: bug

**Comment by philburk** [comment] 2021-04-23 14:32
@donturner - You wrote:
> That would explain why I'm not able to reproduce on my Samsung Galaxy S9+ - because the workaround fixes the issue.

One the Main Screen of OboeTester is a checkBox for enabling the Oboe Workarounds. It is off by default so that we can detect various errors.
