### ISSUE TITLE
toggle to built-in speaker doesn't stop built-in earphone speaker

### ISSUE THREAD

**Issue by hpsaturn** [google/oboe#1770] opened 2023-04-05 15:08 UTC
Android version(s): `13, 12`
Android device(s): `Pixel6 Oriole Android 13, Nokia 3.4 Android 12`
Oboe version: `master source` also in `prefab Oboe 1.7.0` 
App name used for testing:  `Hello Oboe` **

**Short description**

In my own implementation that works fine on Android 11 with Oboe, also with my old OpenSL implementation, I have a weird issue on Android 13, when I toggle the focus from earphone speaker to main speaker and toggle again, the last one doesn't stop and still working.

**Steps to reproduce**
Is hard give steps to reproduce it, because I have a phone application with oboe that works well, that use both streams, an the input and output streams joined to a remote server using two data callbacks and two error callbacks. 

But is possible replicate it (sometimes), when you force the Hello Oboe sample to hot change the output stream. For that I wrote a capture of the second finger touch event to try to force a speaker toggle without stop the stream. After some tries the both speaker still working. 

```java
   void toggleSpeaker(int deviceId){
        Log.i(TAG,"toggle speaker "+deviceId);
        setAudioDeviceIdAsync(deviceId);
    }

   @Override
    public boolean onTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case (MotionEvent.ACTION_DOWN):
                PlaybackEngine.setToneOn(true);
                break;
            case (MotionEvent.ACTION_UP):
                PlaybackEngine.setToneOn(false);
                break;
        }

//        if (event.getPointerCount() == 2) toggleSpeaker(3);
//        if (event.getPointerCount() == 1) toggleSpeaker(3);

        return super.onTouchEvent(event);
    }
```
 
**Expected behavior**
When I'm in a call and I toggle from the main speaker and return to the earphone speaker, Oboe should stop the main speaker.

**Actual behavior**
When I toggle the focus from earphone speaker to main speaker and toggle again, the last one doesn't stop and still working.

**Context**
I have a weird thing more, when the speaker enter to this behavior, and it can't stop, happen after the recording stream has `ErrorDisconnect` error. Details:

```cpp
 D  onEventFromServer - got AAUDIO_SERVICE_EVENT_STOPPED
 D  setState(s#9) from 4 to 13
 W  onEventFromServer - AAUDIO_SERVICE_EVENT_DISCONNECTED - FIFO cleared
 E  callbackLoop: read() returned -899
 D  callbackLoop() exiting, result = -899, isActive() = 0
 D  AAudioStream_requestStop(s#9) called
 D  joinThread_l() pthread_join succeeded
 D  setState(s#9) from 13 to 9
 W  setState(9) tried to set to 9 but already DISCONNECTED
 W  AndroidAudioDeviceManager Input stream Error before close: ErrorDisconnected
 D  AAudioStream_requestStop(s#9) called
 D  joinThread() - but has no thread or already join()ed
 W  requestStop_l() stop callback returned -895, returning early
 D  AAudioStream_close(s#9) called ---------------
 D  release_l(): mServiceStreamHandle = 0x0000036F
 D  joinThread() - but has no thread or already join()ed
 W  requestStop_l() stop callback returned -895, returning early
 D  setState(s#9) from 13 to 11
 V  AudioLogic::trunkstats throughput: IN:    9 pps  501 bps ; OUT:    1 pps   25 bps
 D  setState(s#9) from 11 to 11
 D  setState(s#9) from 11 to 12
 D  ~AudioStreamInternal() 0xb400006e32e4ba90 called
 D  ~AudioStream(s#9) mPlayerBase strongCount = 1
 D  AAudioStream_close(s#9) returned 0 ---------
 W  AndroidAudioDeviceManager Input == S T R E A M  E R R O R == after close: ErrorDisconnected
 V  AndroidAudioDeviceManager destroyAudioRecorder done
 V  AndroidAudioDeviceManager Error stopping stream: ErrorClosed
 V  AndroidAudioDeviceManager Error closing stream: ErrorClosed
 V  AndroidAudioDeviceManager resetting stream..
 I  openStream() INPUT -------- OboeVersion1.7.0 --------
 I  AAudioStreamBuilder_openStream() called ----------------------------------------
 I  rate   =  48000, channels  = 1, channelMask = 0x80000001, format   = 1, sharing = EX, dir = INPUT
 I  device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
 I  usage  =      1, contentType = 2, inputPreset = 6, allowedCapturePolicy = 0
 I  privacy sensitive = false, opPackageName = (null), attributionTag = (null)
 D  configureDataInformation() original HW burst = 48, minMicros = 2000 => SW burst = 96
 D  setState(s#10) from 0 to 2
 I  AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#10 ----------------
 D  AndroidAudioDeviceManager createAudioRecorder done
 D  AAudioStream_requestStart(s#10) called --------------
 D  setState(s#10) from 2 to 3
 D  AAudioStream_requestStart(s#10) returned 0 ---------
 V  AndroidAudioDeviceManager OBOE Record starting with result:<?>
 D  onEventFromServer - got AAUDIO_SERVICE_EVENT_STARTED
``` 

**Implementation details:**

JAVA side speaker toggle:

```java
public void setSpeakerphoneOn( boolean active) {
        LOG.d(TAG,"AudioManager === SPEAKER TOGGLE "+active);
        AudioManager.setSpeakerphoneOn(active);
    }
```

Oboe components:

```cpp
    std::shared_ptr<oboe::AudioStream> mRecordingStream;
    std::shared_ptr<MAudioRecorderCallback> mRecordDataCb;
    std::shared_ptr<MAudioRecorderErrorCallbacks> mRecordErrorCb;

    std::shared_ptr<oboe::AudioStream> mPlayStream;
    std::shared_ptr<MAudioPlaybackErrorCallbacks> mPlaybackErrorCb;
    std::shared_ptr<MAudioPlaybackCallback> mPlaybackDataCb;

    int32_t   mRecordingDeviceId = oboe::kUnspecified;
    int32_t           mPlaybackDeviceId = oboe::kUnspecified;
    const oboe::AudioFormat mFormat = oboe::AudioFormat::I16;
    oboe::AudioApi    mAudioApi = oboe::AudioApi::AAudio;
    int32_t           mSampleRate = oboe::kUnspecified;
    const int32_t     mInputChannelCount = oboe::ChannelCount::Mono;
    const int32_t     mOutputChannelCount = oboe::ChannelCount::Mono;

    int AndroidAudioDeviceManager::createAudioPlayer()
    {
    oboe::AudioStreamBuilder outBuilder;
    mPlaybackErrorCb = std::make_shared<MAudioPlaybackErrorCallbacks>(&*this);
    mPlaybackDataCb  = std::make_shared<MAudioPlaybackCallback>(&*this);
    setupPlaybackStreamParameters(&outBuilder);
    oboe::Result result = outBuilder.openStream(mPlayStream);
    if (result != oboe::Result::OK) {
        logmsg("AndroidAudioDeviceManager Failed to open output stream. Error %s", oboe::convertToText(result));
        mSampleRate = oboe::kUnspecified;
        SLASSERT(result);
    } else {
        // The input stream needs to run at the same sample rate as the output.
        mSampleRate = mPlayStream->getSampleRate();
    }
    int32_t buffer_size = mPlayStream->getFramesPerBurst()*FRAMES_PER_BURST_FACTOR;
    logmsg("AndroidAudioDeviceManager stream buffer player size: %i",buffer_size);
    result = mPlayStream->setBufferSizeInFrames(buffer_size);
    SLASSERT(result);

    warnIfNotLowLatency(mPlayStream);

    loginfo("AndroidAudioDeviceManager createAudioPlayer done");
    return 0;
    }

   oboe::AudioStreamBuilder *AndroidAudioDeviceManager::setupPlaybackStreamParameters(oboe::AudioStreamBuilder *builder) {
      builder->setDataCallback(mPlaybackDataCb)
            ->setErrorCallback(mPlaybackErrorCb)
            ->setDeviceId(mPlaybackDeviceId)
            ->setSampleRate(mSampleRate)
            ->setDirection(oboe::Direction::Output)
            ->setChannelCount(mOutputChannelCount);

      return setupCommonStreamParameters(builder);
   }

    oboe::AudioStreamBuilder *AndroidAudioDeviceManager::setupCommonStreamParameters(oboe::AudioStreamBuilder *builder) {
         builder->setAudioApi(mAudioApi)
            ->setFormat(mFormat)
            ->setFormatConversionAllowed(true)
            ->setSharingMode(oboe::SharingMode::Exclusive)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency);
       return builder;
    }
}

```

**Output Error Callback**:

```cpp
class MAudioPlaybackErrorCallbacks : public oboe::AudioStreamErrorCallback {
  
    void onErrorBeforeClose(oboe::AudioStream *oboeStream, oboe::Result error) {
        m_aadm->m_play_initstate = m_aadm->INIT_ERROR;
    }

    void onErrorAfterClose(oboe::AudioStream *oboeStream, oboe::Result error) {
        
        if (error == oboe::Result::ErrorDisconnected) {
            // Handle stream restart on a separate thread
            m_aadm->destroyAudioPlayer();
            logmsg("AndroidAudioDeviceManager restarting Audio Player..");
            m_aadm->createAudioPlayer();
            m_aadm->m_play_initstate = m_aadm->INIT_NEEDS_START;
            m_aadm->start_playback();
        }
    }
    AndroidAudioDeviceManager *m_aadm;
public:
    MAudioPlaybackErrorCallbacks(AndroidAudioDeviceManager *pManager) : m_aadm(pManager) { }
};
```
Thanks for any help

**Comment by philburk** [comment] 2023-04-05 22:17
@hpsaturn - What is setAudioDeviceIdAsync(deviceId)? What Android APIs does that call?
    Or does it just set mPlaybackDeviceId?

**Comment by flamme** [comment] 2023-04-05 22:20
If only `mPlaybackDeviceId` is being set to asking for a particular device for playback, it may not always guaranteed to get that particular device for playback.

BTW, I assume your apps is doing voice communication. In that case, I'd expect the playback setting the usage as VOICE_COMMUNICATION while it seems leave as default from the code.

**Comment by hpsaturn** [comment] 2023-04-06 09:15
> @hpsaturn - What is setAudioDeviceIdAsync(deviceId)? What Android APIs does that call? Or does it just set mPlaybackDeviceId?

Thanks for your comment. Well, this method is from the official sample of Oboe. I'm using AAudio with Oboe in my implementation. In the sample I choose `Unspecified`. To complement my implementation details, these some initial parameters:    

```cpp
    int32_t   mRecordingDeviceId = oboe::kUnspecified;
    int32_t           mPlaybackDeviceId = oboe::kUnspecified;
    const oboe::AudioFormat mFormat = oboe::AudioFormat::I16;
    oboe::AudioApi    mAudioApi = oboe::AudioApi::AAudio;
    int32_t           mSampleRate = oboe::kUnspecified;
    const int32_t     mInputChannelCount = oboe::ChannelCount::Mono;
    const int32_t     mOutputChannelCount = oboe::ChannelCount::Mono;
```

**Comment by hpsaturn** [comment] 2023-04-06 09:20
> BTW, I assume your apps is doing voice communication. In that case, I'd expect the playback setting the usage as VOICE_COMMUNICATION while it seems leave as default from the code.

Yes, in the Java side we have:

```java
private static class Api26AudioManagerCompat extends AudioManagerCompat {

        private static AudioAttributes AUDIO_ATTRIBUTES = new AudioAttributes.Builder()
                .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
                .setLegacyStreamType(AudioManager.STREAM_VOICE_CALL)
                .build();

        private AudioFocusRequest audioFocusRequest;

        private Api26AudioManagerCompat(@NonNull Context context) {
            super(context);
        }

        @Override
        public void requestCallAudioFocus() {
            if (audioFocusRequest != null) {
                LOG.i(TAG, "requestCallAudioFocus ignoring...");
                return;
            }

            audioFocusRequest = new AudioFocusRequest.Builder(AUDIOFOCUS_GAIN)
                    .setAudioAttributes(AUDIO_ATTRIBUTES)
                    .setOnAudioFocusChangeListener(onAudioFocusChangeListener)
                    .build();

            int result = audioManager.requestAudioFocus(audioFocusRequest);
            if (result != AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
                LOG.w(TAG, "requestCallAudioFocus failed: " + result);
            }
        }

        @Override
        public void abandonCallAudioFocus() {
            if (audioFocusRequest == null) {
                LOG.i(TAG, "abandonCallAudioFocus ignoring...");
                return;
            }

            int result = audioManager.abandonAudioFocusRequest(audioFocusRequest);
            if (result != AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
                LOG.w(TAG, "abandonCallAudioFocus failed: " + result);
            }

            audioFocusRequest = null;
        }
    }
```

**Comment by hpsaturn** [comment] 2023-04-11 11:03
I don't if this can help us, but I did a tester that "reproduce" the behavior. Keep in mind that is very different to my implementation, because there, in my implementation, I have a continuous stream working (input: microphone and output: earphone or main speaker) in a "communication" context, but the result it's the same, the speaker keep running when it should be stopped by the system. 

https://github.com/hpsaturn/oboe/tree/issue_1770_tester

## Steps to launch it

1. clone this branch from this fork
2. build and install in a Android 13 Oriole phone
3. launch the app
4. select earphone speaker (playback device)
5. touch the screen to start the audio generator
6. wait 5 seg, an internal timer should start the speaker toggle that produce a `ErrorDisconnected`
7. tap again the screen, we have the TWO speakers working at the same time.

In Android 12 the behavior is different, after the error only we have the main speaker working.

Also note that I added a new class in the sample `AudioManagerCompat.java`

## Video demo

https://user-images.githubusercontent.com/423856/231140817-87cc0165-3ece-4361-9258-3a16cdbd37f0.mp4

**Comment by flamme** [comment] 2023-04-11 22:05
@hpsaturn, thanks for sharing all the context and demo! It really helps!

I tried your demo and it seems everything work as intended on my side. For the first pressing, the audio is on earpiece. And then 5 seconds later, there is a disconnection. Tap again the screen, the output is on speaker. You may try to run `adb shell dumpsys media.audio_flinger` to check actual output device.

I agreed that on my device, when the output device was speaker, it was not only coming out from the bottom/main speaker, but still have sound coming out from other places. I believed that was due to the audio was stereo. And one channel was coming out from the bottom speaker, and the other one was from other places. 

You can easily verify by using Oboe Tester following the steps.
1. Open Oboe Tester
2. Select TEST OUTPUT
3. Select channels as 2
4. Unchecked the channels box at the bottom to mute a certain channel.

With the above steps, you can verify how the stereo audio work on your device.

**Comment by hpsaturn** [comment] 2023-04-11 22:37
Thanks for your answer. Here is late, but I want to say only that I have the same behavior than you but in Android 11. In Android 13 is very clear in our implementation that the speaker doesn't stop and we have two outputs in the middle of the call.. Also we can't return to only earphone speaker. 

Tomorrow I will to test with Oboe Tester like you mentioned. Thanks again.

**Comment by hpsaturn** [comment] 2023-04-14 10:35
> You can easily verify by using Oboe Tester following the steps.
> 
>     1. Open Oboe Tester
>     2. Select TEST OUTPUT
>     3. Select channels as 2
>     4. Unchecked the channels box at the bottom to mute a certain channel.

Hi @flamme it is weird, with the Oboe tester with these parameters and also without them, I have "Error: Start failed with -895" message. I still working on review some deprecated methods in my Java side, but I think that we have a problem with Android 13 in these devices.

**Comment by hpsaturn** [comment] 2023-04-14 10:39
I did a pull request #1780 to share my device information from Oboe tester app. Here my device report:
[oriole_device_report.txt](https://github.com/google/oboe/files/11231877/oriole_device_report.txt)

**Comment by hpsaturn** [comment] 2023-04-17 14:39
Good news, the issue was fixed on Java side with a workaround, forcing the communication mode with the AudioManager. I don't know now, if this behavior is ok or is a issue, but the only thing is that Audio Manager in Android 13 don't remember the original devices and it can't not restore again. For this reason I forced it.

**Comment by philburk** [comment] 2023-04-19 22:43
Thanks for the #1780 PR!

If the issue is just that the sound comes out both speakers then that is not a bug. Different devices and versions will behave differently.

>  the only thing is that Audio Manager in Android 13 don't remember the original devices and it can't not restore again.

I'm not sure what that means. But it may be a bug. If that is a different issue then please start a new bug so we can have a fresh look. Then I will close this bug.

**Closed** 2023-04-20 19:38 UTC
Labels: bug
