### ISSUE TITLE
App similar to LiveEffects running on Samsung S9 does not make any sound

### ISSUE THREAD

**Issue by 254845158** [google/oboe#980] opened 2020-08-14 18:58 UTC
Device: Samsung S9
Android version: Android 10
Oboe version: 1.4.3
App used: https://play.google.com/store/apps/details?id=com.learning.microphone

Description of problem:
The app seems to run fine with no crashes and is able to open streams. However, once the streams are opened, no sound from the device is produced, i.e. when the streams are not opened, the phone itself can still output sound when buttons are clicked or volume bar is moved, but when the streams are on, the phones seem to be muted. 

Expected behaviour:
Phone output the processed sound when the user speaks to the mic.

Actual behaviour:
The phone is muted.

The app has been tested on devices with various versions which worked fine, however, this seems to be a problem with Android 10 as this problem has also appeared during a test with Huawei P30 which was operating on Android 10 and according to the tester, the devices seem to be muted as well.

Looking forward to your feedback.

Thank you very much.

**Comment by dturner** [comment] 2020-09-15 16:44
Just tested LiveEffect on a Samsung S9 running Android 10. It worked as expected with audio from the microphone being played through the speakers. I also tested your app (which was good of me because we're not here to QA commercial applications 😉 ) and it worked as I would expect. 

If you can reproduce the issue using the LiveEffect sample then please add to this issue. Closing for now.

**Closed by dturner** 2020-09-15 16:44 UTC
Labels: Samsung

**Comment by 254845158** [comment] 2020-09-15 16:59
Sorry for that, I thought any general issues can be posted here. Thank you for testing.
