### ISSUE TITLE
OboeTester - Significant Audio Recording Glitches with Pixel 2

### ISSUE THREAD

**Issue by ShariqM** [google/oboe#557] opened 2019-06-18 23:25 UTC
When recording audio using the OboeTester Record and Play feature with default settings on the Pixel 2, significant audio glitches are introduced. Speech is unintelligible, see here: https://soundcloud.com/anon-ymous-647326941/sets/pixel-2-glitch

If you change the sample rate to 8000hZ, there is no issue.

- Was any code changed? No
- How to reproduce?
1. Install OboeTester on a Pixel 2 device.
2. Hit Record and Play.
3. Record some audio, at least 5 seconds, with all default settings.
4. Play Recording, you will hear glitches.
- Other points of interest
1. This happens when using any pixel 2 microphone and when using an external microphone on my earbuds. Changing channels or PCM_16 doesn't solve the problem.
2. There is no audio glitch at any sample rate below 48000 is used. My guess is the Android Resampler fixes this bug somehow.
3. LiveEffect does not have this audio glitch issue by default, even at 48000hZ. However, if you use blocking reads instead of non-blocking, this audio glitch arises. Git Diff is here: https://pastebin.com/raw/sNeykq7Y
- Android Version: 9.0

**Comment by atneya** [comment] 2019-06-19 18:11
I am unable to reproduce this issue on Android P with a Pixel 2XL with the latest version of Oboe . Is that what you are using?

**Comment by philburk** [comment] 2019-06-19 19:34
Thank you for reporting this. We have some questions that will help us track this down.

Do the glitches happen every time or just sometimes?

Which build of Android 9.0 are you using? Look in Settings > About Phone
scroll down to Build Number

What happens if you check the Exclusive box? Does it sound better? Does it say "SHARED" or "EXCLUSIVE" when you open?

How does it sound if you select "Perf: NONE" instead of LOW_LATENCY?

After "devID=", does it say "MMAP" or "Legacy" after you Start?

Can you please make a **short** recording and then hit the Share button. That will let you save an exact recording to an email or Google Drive. Then please attach the recording to a comment on this Issue report.  Then we can analyze the recording in better detail.

**Comment by ShariqM** [comment] 2019-06-20 01:50
@atneya 
* Commit ID: commit 77ea1882f072d0a607247b722e7cc985a1edb6d8 (June 12th)
* I'm using a Pixel 2 (not XL). But I think someone using my app is hitting the same issue and they have a Pixel 2 XL.

@philburk 
* The glitches happen nearly every time, but the degree varies, sometimes speech is unintelligible sometimes it is intelligible but there is still an intolerable number of glitches. It usually starts at around second 4 and continues indefinitely.
* Build number: PQ3A.190605.003O
* It sounds bad in exclusive or shared mode, can't tell the difference. One time there was no glitches in shared mode but it was an outlier. Screenshots of settings in attached zip. 
* With "Perf: NONE" there is a bit of static but nothing like the glitches with "Perf: LOW_LATENCY". I attached audio. Audio in attached zip.
* devID = 259, MMAP

[audio_glitch.zip](https://github.com/google/oboe/files/3308440/audio_glitch.zip)

Other notes:
* Sometimes when I record myself saying "1, 2, 3, 4, ..." when I hit play I only hear "2, 3, 4, ..." i.e. the beginning gets cutoff, not sure if that's an OboeTester bug or Oboe bug.
* From my investigation in issue/358 it seemed like stream->read() was returning sound containing audio glitches without reporting any kind of error. So I don't think it has anything to do with onAudioReady() or output buffering. This was with block reads though. Let me know if you want more details.

**Comment by philburk** [comment] 2019-06-20 17:36
@ShariqM - thanks for the info
We were using PQ2A so we will try PQ3A.190605.003O

Thanks for the WAV files. I notice that both of them were recorded at extremely volume.
The LOW_LATENCY one was chopped up into 1 msec buffers, which indicates a timing error related to the DSP tracking.
The NONE one was just noisy, I think because of the low volume.

> devID = 259, MMAP

259! We have seen issues with some USB headsets. Were you recording with a USB headset? Which make and model?

While recording, can you enter:
      adb shell dumpsys media.audio_policy
and attach the result?

**Comment by ShariqM** [comment] 2019-06-20 18:25
Good call. Yes, it appears to be an issue with the USB-C headsets. Strangely, even if I select to use the Pixel-2 Microphone inside OboeTester when using the USB-C headset the audio glitch still arises. I cannot run "adb shell dumpsys media.audio_policy" *while* recording because I need the USB-C headset plugged into the single slot in my phone. Can I run it immediately after?

Audio Glitch arises on [1] and [2] but not on [3]. Concretely the issue is: If audio is recorded at the native sample rate of **48kHZ** while a USB-C headset  is plugged in there is going to be audio glitches on the Pixel 2, regardless of which microphone is used.


[1] https://www.amazon.com/gp/product/B07MMZF466/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1 [USB-C + Microphone]
[2] https://www.amazon.com/gp/product/B07LF8HNQ9/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 [USB-C + Microphone]
[3] https://www.amazon.com/gp/product/B0038W0K2K/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 [3.5mm Audio Jack + Google USB-C to 3.5mm adapter]
[3]

**Comment by ShariqM** [comment] 2019-06-20 19:00
@philburk I connected to adb over WiFi and got the log you requested (attached).
[android_audio_glitch.txt](https://github.com/google/oboe/files/3311758/android_audio_glitch.txt)

**Comment by ShariqM** [comment] 2019-06-20 19:30
Sorry for spam: It does still happen with non-usb non-headsets [3] but very infrequently. Maybe 1/20 recordings, I'm not sure.

[3] https://www.amazon.com/gp/product/B0038W0K2K/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 [3.5mm Audio Jack + Google USB-C to 3.5mm adapter]

**Comment by philburk** [comment] 2019-06-21 18:08
@ShariqM - Thanks for the details. And the dumpsys.

> Concretely the issue is: If audio is recorded at the native sample rate of 48kHZ while a
> USB-C headset is plugged in there is going to be audio glitches on the Pixel 2,
> regardless of which microphone is used.

OK, thanks. That is a very important clue. I suspect the DSP may be doing some resampling, which causes variations in the burst timing.

Also thanks for the Amazon links. We should be able to reproduce this in-house.

**Comment by ShariqM** [comment] 2019-06-28 07:54
@philburk Is there anyway I could get a timeline on this? My business relies on Oboe and one of my users has this issue.

**Comment by philburk** [comment] 2019-07-03 00:24
@shariqm I think this might related to internal bug b/123643363 in AAudio.
If that fixes your issue then it will still take a while before you will see that in many phones.
So we should look at a workaround in the meantime.

For your app, do you need low latency? If not then I recommend using PerformanceMode::None.

If you need low latency then are you using full duplex? In other words, are you playing audio at the same time?

I may be able to suggest a workaround for low latency but it is complicated and we need to check it here first.
The issue is be that there may not be enough data in the buffer.
The workaround involves checking getFramesWritten and getFramesRead. Do not read if
    framesWritten - framesRead < (2 * framesPerBurst)
just sleep for one burst period and try again.

We will try to prepare a workaround example if we can reproduce the issue you describe.

**Comment by ShariqM** [comment] 2019-07-03 21:59
@philburk I see. Yeah, I need low latency. I am using full duplex. Will your suggestion work in that case? I can give it a try.

**Comment by philburk** [comment] 2019-07-09 18:00
I tested on Alleeco headset on Pixel 2 running July 1 build of qt-r1-dev. Recording and Echo test passed.

On PQ3A.190605.003 (5524043) the recording through Alleeco became very glitchy after about 4 seconds! Glitches were 48 frames long. EXCLUSIVE MMAP mode.
I then recorded with Alleeco plugged in but though first microphone listen. Same glitches!
I then recorded with nothing plugged in. PASS
So I can reproduce the bug.

**Comment by philburk** [comment] 2019-07-09 19:52
PQ1A on Pixel 2 XL
Recording used Legacy path. (Why?) PASS
Recording through built-in microphone while Alleeco plugged in. MMAP - FAIL
Recording through Alleeco on MMAP - FAIL

QPP1.190205.018.B4 (5347935) qt-preview1 - FAIL
QPP2.190228.023.A1 (5437700) qt-preview2 - PASS

What CLs are in QPP2?
ag/5930381 - audio: cleanup code that reads timing model - Merged Feb 1, 2019
Not likely. I cannot find any CLs that look related between QPP1 and QPP2.
Maybe something changed in DSP or HAL?

**Comment by philburk** [comment] 2019-07-09 21:26
testing on Pixel 3 (blueline-userdebug)
PQ1A.190105.004 (5148680) - Legacy (why?) PASS
PQ1A.190105.004 (5148680) - MMAP - PASS
QPP1.190205.018.B4 (5347935) - MMAP - PASS
qt-r1-dev as of July 9th - MMAP - PASS

This glitch seems to be device specific. I think Qualcomm may have made some changes to the DSP code that improved the timing of the bursts.

**Comment by philburk** [comment] 2019-07-09 21:29
@ShariqM you asked:
> Yeah, I need low latency. I am using full duplex. Will your suggestion work in that case? I can give it a try.

Yes, that technique works best with Full Duplex because you can do read()s of the input from a high priority output callback.

Try modifying the new FullDuplexStream inLiveEffect.
https://github.com/google/oboe/blob/master/samples/LiveEffect/src/main/cpp/FullDuplexStream.h

**Comment by ShariqM** [comment] 2019-07-15 06:19
@philbuk Not sure what you want me to do. Something like this? Don't quite understand why getOutputStream would affect getInputStream if so.
```

bool notReadyForRead() {
    return getOutputStream()->getFramesWritten() - getInputStream()->getFramesRead() < (2 * framesPerBurst))
}

if (notReadyForRead() {
            callbackResult = onBothStreamsReady(
                    mInputBuffer.get(), 0 /* (framesRead) */,
                    audioData, numFrames
            );
} else {
        // Read data into input buffer.
        oboe::ResultWithValue<int32_t> result = getInputStream()->read(mInputBuffer.get(),
                                                                       numFrames,
                                                                       0 /* timeout */);
        if (!result) {
            callbackResult = oboe::DataCallbackResult::Stop;
        } else {
            int32_t framesRead = result.value();

            callbackResult = onBothStreamsReady(
                    mInputBuffer.get(), framesRead,
                    audioData, numFrames
            );
        }
```

**Comment by philburk** [comment] 2019-07-17 21:20
notReadyForRead() should only be looking at the INPUT stream!

**Comment by jcusters** [comment] 2019-09-11 08:51
Hi guys,
I can confirm that this issue is also on the:
**Pixel XL Android V9 ( no more info reported )**
 Same Recording glitches after 6 minutes of good recording, with internal microphone.
**Huawei Mate 20 Lite Android version starting from  V9 up to V9.1.0.229**
 Same Recording glitches from the start, with internal microphone
 The same Huawei with Android 8.1 performed well !
Our workaround at the moment is to switch of the LOW_LATENCY , alas.
Hope they nail it soon.

**Comment by philburk** [comment] 2022-04-20 22:00
I believe this was caused by jitter in the MMAP timing caused by resampling in the DSP.  b/123643363
That was fixed in QT.
So I am closing.

**Closed by philburk** 2022-04-20 22:00 UTC
Labels: bug, P1
