### ISSUE TITLE
Why change the drumthumper audio crash, is there something wrong with my wav audio?

### ISSUE THREAD

**Issue by kevin-zheng12** [google/oboe#777] opened 2020-01-31 03:04 UTC
[wav.zip](https://github.com/google/oboe/files/4137391/wav.zip)

Android Version(s): 8.1.0
Android Device(s): DUB-AL00
Oboe Version: The latest version

**Short Description**
I replaced the default drumthumper audio with a flash back
**Steps To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

If applicable, please attach a recording of the sound.

**Comment by philburk** [comment] 2020-01-31 03:41
I don't understand the question. And the bug report is empty.
I suspect this is a duplicate of #768

**Comment by kevin-zheng12** [comment] 2020-01-31 04:16
I downloaded oboe and ran drumthumper sample, then I replaced SnareDrum.wav in the sample with my own audio, but it crashed as soon as it was run

**Comment by kevin-zheng12** [comment] 2020-01-31 04:19
![1580444269804](https://user-images.githubusercontent.com/60495642/73512216-bfc31a00-4423-11ea-959c-235f6c39aec5.jpg)
![1580444276352](https://user-images.githubusercontent.com/60495642/73512221-c3ef3780-4423-11ea-9b0a-ddafff379ce6.jpg)
I have uploaded the wav file and cut the picture, please help me answer, thank you

**Comment by kevin-zheng12** [comment] 2020-01-31 04:23
This is my audio, whichever one will crash
[wav.zip](https://github.com/google/oboe/files/4137581/wav.zip)

**Comment by philburk** [comment] 2020-02-03 02:33
Thank you for providing more information. We should be able to reproduce this now. I am reopening the bug.

**Comment by android-usb** [comment] 2020-02-07 17:47
the wav file snare3.wav contains a STEREO sample. DrumThumper requires a MONO sample file. For simplicity/clarity (and because we controlled the wav files being used), we did not provide any handling for non-conforming files.
Perhaps we will in and update.

**Closed by android-usb** 2020-02-07 17:47 UTC
Labels: bug
