### ISSUE TITLE
Fatal  signal 4 (SIGILL), code 2, fault addr

### ISSUE THREAD

**Issue by aljohnston112** [google/oboe#685] opened 2019-10-31 13:17 UTC
Android Version(s): 14-29
Android Device(s): AlcatelA30Fierce API 24 and qemu-system-i386
Oboe Version: 1.2.0

**Short Description**
I followed the getting started and the app keeps stopping. I can hear a short sine wave play once or twice and then the app crashes with the error in the title.
**Steps To Reproduce**
Follow the getting started and run the app
**Expected behavior**
To hear a sustained sine time without a crash
**Actual behavior**
Explained in short description 
**Additional context**
Here's a stackoverflow post on the issue
https://stackoverflow.com/questions/58628935/why-does-the-sample-code-called-oboesineplayer-from-oboe-keep-stopping-on-androi?noredirect=1#comment103587164_58628935
If applicable, please attach a recording of the sound.

**Comment by philburk** [comment] 2019-11-02 02:22
On stackoverflow someone wrote:
"It might be because the object oboeSinePlayer is destroyed when the function Java_com_example_gettingstartedoboe_MainActivity_oboeSinePlayer returns, because it is a local variable."

That sounds right to me. Try putting 
     OboeSinePlayer oboeSinePlayer;
outside the function.

**Comment by aljohnston112** [comment] 2019-11-02 08:32
Same issue

**Comment by philburk** [comment] 2019-11-02 17:21
OK, but leave the oboeSinePlayer outside the function because the program will definitely crash if it is declared in a function call.

We need to figure out whether the problem is with your code or the device.
Please try building and running the sample programs in the oboe repo.
https://github.com/google/oboe/tree/master/samples

If they fail then we can debug the sample code on that device.

Also please try your program on another device. You could try an emulator if you only have the one phone.

**Comment by cyb3rc0lby** [comment] 2019-11-18 03:35
did you make sure that the callback class is also not going out of scope? same thing happened to me.

**Comment by philburk** [comment] 2019-11-18 18:20
I'll assume the problem was a scope issue. Closing due to inactivity.

**Closed by philburk** 2019-11-18 18:20 UTC
Labels: bug
